project:
  type: website

website:
  title: "Russell Lewis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - cv.qmd
      - projects.qmd
      - publications.qmd
      - lectures.qmd
      - teaching.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

