---
layout: cv
title: Curriculum Vitae
---
## Russell Edward Lewis
I am an Associate Professor of Infectious Diseases in the Department of Molecular Medicine at the University of Padua and a clinical pharmacologist. I have over 25 years experience in laboratory and clinical research of antimicrobial and antifungal pharmacokinetic and pharmacodynamics in immunocompromised hosts. My current research focuses on the development and incorporation of prognostic risk models and decision/dosing support tools for fungal infections and multidrug resistant bacteria.

<div id="webaddress">
<a href="https://www.medicinamolecolare.unipd.it/category/ruoli/personale-docente?key=7F6B3194E9D1AA6B33AE5DDA22979880">UNIPD Webpage</a>
| <a href="http://russlewisid.com">Personal website</a>
</div>
<br>
last updated: May 25, 2024

## Contact information

(Office): Cia Gabelli 63, 35121 Padova <br>
russelledward.lewis@unipd.it <br>

(Home): Via Fortunato Venanzio, 60 <br>
Treviso, Italy 31100 <br>
+39 345 309 9843 <br>
russ.e.lewis@gmail.com <br>
www.russlewisid.com

## Birthdate

03-June-1972, Salina, Kansas, United States of America

## Citizenship

United States of America; Permanent Residency Visa, Italy

## Research Profiles

- ORCID ID: <a href="https://orcid.org/0000-0002-2002-4339">0000-0002-2002-4339</a>
- Google scholar: <a href="https://scholar.google.com/citations?hl=en&pli=1&user=5mYwM2gAAAAJ">Profile</a>
- SCOPUS: <a href="https://www.scopus.com/authid/detail.uri?authorId=7404846664">7404846664</a>

## Professional Experience

`2023-`
__Associate Professor of Infectious Diseases (MED/17) | Dipartimento di Medicine Molecolare, Università degli studi di Padova__  <br> Padova, Italy

`2013-2023`
__Associate Professor of Infectious Diseases (MED/17) | Dipartimento di Scienze Mediche e Chirurgiche, Alma Mater Studiorum Università di Bologna__  <br> Bologna, Italy

`2011-2012`
__Full Professor with Tenure, Department of Clinical and Administrative Sciences, University of Houston College of Pharmacy__ 
<br> Houston, Texas

`2005-2011`
__Associate Professor with Tenure, Department of Clinical and Administrative Sciences, University of Houston College of Pharmacy__ 
<br> Houston, Texas

`2005-2007`
__Chair, ad interm,Department of Clinical and Administrative Sciences, University of Houston College of Pharmacy__ 
<br> Houston, Texas

`2000-2011`
__Adjunct Faculty, Division of Infectious Diseases, Infection Control and Employee Health, The University of Texas M.D. Anderson Cancer Center__ 
<br> Houston, Texas

`1999-2005`
__Assitant Professor, Department of Clinical and Administrative Sciences, University of Houston College of Pharmacy__ 
<br> Houston, Texas

## Education 

`1990-1996`
__Doctor of Clinical Pharmacy (Pharm.D.), University of Kansas__ 
<br> Lawrence, Kansas

`1996-1997`
__Clinical Pharmacy Residency, Barnes-Jewish Hospital, Washington Univeristy Medical Center__ 
<br> St. Louis, Missouri

`1997-1999`
__Infectious Diseases Research Fellowship, University of Iowa Colleges of Pharmacy and Medicine__ 
<br> Iowa City, Iowa

## Training courses

`2005`
__Woods Hole Marine Biology Laboratories: Molecular Mycology: Current Approaches to Fungal Pathogenesis__ 
<br> Woods Hole, Massachusetts

## Professional Licensure

`1997-`
__Licensed Pharmacist__: Missouri (Inactive; Previously licensed in Texas)

`2001-2015`
__Board Certified Pharmacotherapy Specialist__
<br> Added qualifications in infectious diseases

## Clinical Experience

`2024-Present`
__Hematopoetic Stem Cell Transplant and Cellular Therapy, UOC Ematologia, Dipartimento di Medicina Interna,
Ospedale Ca' Foncello, ULSS2 - Marca Trevigiana__
<br>
Treviso, Italy

`2012-2023`
__UO Malattie Infettive, IRCCS Policlinico S. Orsola-Malpighi, University of Bologna__ 
<br> Bologna, Italy

`2000-2011`
__Clinical Staff (Pharmacy) and Faculty (Medicine) Infectious Diseases Consultation Services, The University of Texas M.D. Anderson Cancer Center__ 
<br> Houston, Texas

`1997-1999`
__Clinical Adjunct Faculty Infectious Diseases/Internal Medicine, University of Iowa College of Pharmacy__ 
<br> Iowa City, Iowa

`1996-1997`
__Clinical Pharmacist, Barnes-Jewish Hospital__ 
<br> St. Louis, Missouri

`1995-1996`
__Pharmacy Intern, St. Francis Regional Hospital__ 
<br> Topeka, Kansas

`1992-1995`
__Laboratory Research Assistant, Department of Pharmacology and Toxicology, University of Kansas School of Pharmacy__ 
<br> Lawrence, Kansas

## Post-doctoral students

`2002-2004`
__Nathan Widerhold, Pharm.D.__ 
<br> Thesis: Pharmacodynamics of caspofungin in a murine model of invasive aspergillosis
<br> Houston, Texas 

`2018-2021`
__Irene Zaghi, M.D.__ 
<br> Infectious Diseases Specialization Thesis: Bayesian Diagnostic Meta-Analysis of Blood Time To positivity for Predict Infection Outcome and Catheter-Related Bloodstream Infections
<br> Bologna, Italy

## Doctoral students

`2014-2015`
__Irene Zaghi, M.D.__
<br> Thesis: Diagnostic Meta-Analysis of Serum Bactericidal Testing
<br> Bologna, Italy 

`2018-2019`
__Giulia De Luca, M.D__ 
<br> Thesis: Use of State Transition Models to Explore the Utility of Selective Digestive Tract Decontamination in Patients Colonized with Carbapenem-Resistant Enterobacteriaceae
<br> Bologna, Italy

`2019-2020`
__Mayleko Mohamedwais, M.D.__ 
<br> Thesis: Development and internal validation of a model to predict early invasive mold disease risk in patients undergoing allogeneic hematopoietic stem cell transplantation 
<br> Bologna, Italy

`2021-2022`
__Nicola Montovani, M.D.__ 
<br> Thesis: Incorporation of genetic risk factors in a clinical risk prediction score for invasive mold disease for patients undergoing treatment for hematological malignancies
<br> Bologna, Italy

## Teaching Experience

`2023-Present`
<br> **University of Padua**, Padua, Italy

<br> **University of Padua**, Padua, Italy


`2023-Present`
<br> **University of Padua**, Padua, Italy
<br> MEP 2491 Infectious Diseases
- Principles of antibiotic therapy
- Antibiotic resistance in ESKAPE pathogens
- Antibiotic allergies
- Fever of unknown origin
- Invasive fungal infections
- Infectious diarrhea
- Intraabdominal infections
- Parasites-malaria and leishmaniasis
 
`2021-2023`
__9730- Global Health, Antimicrobial Therapy and Vaccines__
<br> **University of Bologna**, Bologna, Italy
<br> Course website: <a href="https://www.uniboglobalhealth.com/">www.uniboglobalhealth.com</a> 

`2014-2021`
__79947 – Malattive Infettive II__ 
<br> **University of Bologna**, Bologna,Italy
- Antimicrobial pharmacokinetics and pharmacodynamics
- Antifungal pharmacokinetics and pharmacodynamics

`2014-2021`
__PHAR 5208 Infectious Diseases Therapeutics, Course coordinator__ 
<br> **University of Houston College of Pharmacy**, Houston, Texas 
- _The clinician and the microbiology laboratory_
- Aerosolized and percutaneous antibiotic dosing
- Immunology of ID
- Antibiotic hypersensitivity and allergy
- Vaccination
- Antifungal therapy

`2007-2011`
__PHAR 4308. Cellular Life Sciences II__ 
<br> **University of Houston College of Pharmacy**, Houston, Texas 
- Adversarial pathogen strategies during infection, Parts 1-3 
- Immunobiologicals used in transplant and oncology

`2007-2011`
__PCOL 6371-Advanced Pharmacology II__ 
<br> **University of Houston College of Pharmacy**, Houston, Texas 
- Principles of Host Immunity 
- Immunopharmacology
- Pharmacology of anti-inflammatory agents

`2000-2010`
__PHCA 5209 Infectious Diseases Pharmacotherapeutics II__ 
<br> **University of Houston College of Pharmacy**, Houston, Texas 
-  Essentials of in vitro testing of antimicrobials 
-  Molecular mechanisms of antibacterial resistance
-  Quinolone antibiotics 
-  Macrolides, lincosamides, streptogramins, and linezolid 
-  Systemic antifungal agents
-  Immunology of Infectious Diseases 
-  Vaccinations

`2007-2010`
__University of Houston Residency Certificate Program__ 
<br> **University of Houston College of Pharmacy**, Houston, Texas 
- Academic careers
- Scientific publication

`1999-2011`
__PHAR 5581. Advanced Pharmacotherapeutics, Co-course coordinator__
<br> **University of Houston College of Pharmacy**, Houston, Texas 
- Systemic Fungal Infections 
- Infective Endocarditis
- Sexually Transmitted Diseases
- Septic Meningitis 
- Tuberculosis 
- Immunology of auto-immune diseases 
- Drug Hypersensitivity 

`2001-2011`
__PHAR 5229 Research Methodologies in Pharmaceutical Research__ 
<br> **University of Houston College of Pharmacy**, Houston, Texas <br>
- Animal Models in Pharmaceutical Development

`2001-2011`
__PHAR 5682 Infectious Diseases Clinical Clerkship
<br> University of Houston College of Pharmacy and The University of Texas M.D. Anderson Cancer Center,__ Houston, Texas
- Hematological Malignancies /Hematopoetic Stem Cell Transplant Consult Service
- Solid Tumor Malignancies Consult Service
- Intensive Care Unit Consult Service

`2002-2003`
__PHAR 5372 –Pharmacy Law and Ethics, Course Coordinator__ 
<br> **University of Houston College of Pharmacy**, Houston, Texas <br>

`2001-2005`
__PHPR 646 – Pharmacotherapy I. Invited lecturer__ 
<br> **University of Kansas School of Pharmacy**, 
<br> Kansas Medical Center, Kansas City, Kansas 
- Invasive fungal infection
- Sepsis

`2001-2011`
__Infectious Diseases Fellows Core Curriculum__ 
<br> **The University of Texas M.D. Anderson Cancer Center and Baylor College of Medicine**, Houston, Texas
- Antibiotic and Tumor-Related Fever
- New Treatment Modalities for Acute and Chronic Leukemia 
- Infectious Complications in Chronic Lymphocytic Leukemia 
- The Pharmacology of Sepsis
- Iatrogenic Immunosuppression 
- Overview of Antifungal Pharmacology
- Overview of Immunosuppression Associated with Cancer Chemotherapy 
- Antibiotic Hypersensitivity

`2000-2001`
__Diabetes TX-Pharm Elective 
<br> University of Houston College of Pharmacy__, Houston, Texas
- Infections in the Diabetic Patient

`2000-2011`
__PHAR 5365 Pharm.D Seminar__ 
<br> **University of Houston College of Pharmacy**, Houston, Texas

`1998-1999`
__Pharmacotherapy IV__
<br> **University of Iowa College of Pharmacy**, Iowa City, Iowa 
- Febrile neutropenia
- Infective endocarditis

`1997-1999`
__Pharmacotherapy IV, Group case discussion leader__ 
<br> **University of Iowa College of Pharmacy**, Iowa City, Iowa 

`1997-1999`
__Introduction to Pharmaceutical Care, Group leader__ 
<br> **University of Iowa College of Pharmacy**, Iowa City, Iowa 

`1997-1999`
__Instructor, Infectious Diseases Research Elective__ 
<br> **University of Iowa College of Pharmacy**, Iowa City, Iowa 

`1997-1999`
__Instructor and context evaluator, Honors Seminar__ 
<br> **University of Iowa College of Pharmacy**, Iowa City, Iowa 

`1996-1997`
__Adjunct Clinical Instructor at Barnes-Jewish Hospital__ 
<br> **St. Louis College of Pharmacy**, St. Louis, Missouri
- Infectious Diseases Clerkship 
- Internal Medicine Clerkship
- Critical Care Clerkship
- Ambulatory Care Clerkship (VA Medical Center)

`1996-1997`
__Infectious Diseases Pharmacotherapy__ 
<br> **St. Louis College of Pharmacy**, St. Louis, Missouri
- Overview of Microbiological Testing 
- Overview of Antibacterial Resistance

## Invited Lectures

`2022`
__Importance of pharmacokinetics/pharmacodynamics in the immunocompromised host__
<br> 21st Immunocompromised Host Society Symposium on Infections in the Immunocompromised Host, Basel, Switzerland

__Antifungal prophylaxis in the tageted chemotherapy era__
<br> University of Manitoba, Hematology-Infectious Diseases Conference (Virtual), 
<br> Winnipeg, Manitoba, Canada
<br> University of Alberta, Hematology Grand Rounds (Virtual)
<br> Edmonton, Alberta, Canada

__Overview of the antifungal pipeline in 2022__
<br> F2G Medical Laison Training (Virtual)

`2021`	
__Antimicrobial PK in critically-ill: CRRT, ECMO and Drug interactions__
<br> European Hematology (Virtual). Association Annual Meeting. June 11, 2021.

__Antifungal pipeline for invasive candidiasis__
<br> Bertino bloodstream infection meeting (Virtual hybrid), Bertino (Romagna), Italy

__Antifungal stewardship best practices__
<br> SHAPE 2021 Meeting (Virtual)

__Antifungal PK/PD in the critically ill and hematology patient__
<br> Antifungal therapy: Myths and truths (Virtual hybrid), Brazil

__Antifungal TDM in critically-ill patients, which drugs and how?__ 
<br> ATHENA 2021 Conferernce (Virtual hybrid), Athens, Greece

__What is the right dose for CRRT and ECMO?__
<br> ATHENA 2021 Conferernce (Virtual hybrid), Athens, Greece

__Spiraling empiricism vs. science: The delimma of breakthrough fungal infections__
<br> Society of Infectious Diseases Pharmacists 2021 Fall Business Meeting (Virtual)

__Antifungal therapy in the era of targeted chemtoherapy for hematological maliganancies__
<br> Canadian Infectious Diseases Meeting (Virtual)

__Antifungal therapy considerations in the tageted chemotherapy era__
<br> Canadian Hematology National Conference (Virtual)

`2020` 
__COVID-19 and invasive aspergillosis: Lessons learned.__ 
<br> Gilead Care Webinar Series (Virtual). 

__The growing impact of targeted chemotherapy on the treatment of invasive fungal diseases__ 
<br> Ambisome 30 year Anniversary Symposium. (Virtual). 

__Optimizing antifungal dosing for bloodstream and intraabdominal candidiasis__
<br> Gilead CARE Meeting, Brazil (Virtual)

__Difficult cases in managing antifungal drug interactions with targeted chemotherapies__
<br> Gilead CARE Meeting, Brazil (Virtual)

__Managing drug interactions in the era of targeted therapies for hematological malignancies__
<br> Kings College London Hematology Grand Rounds (Virtual)

`2019`
__How I manage drug interactions in the era of targeted therapies for hematological malignancies__ 
<br>12th Annual Gilead Care Meeting, Paris, France	

__Pharmacological basis for treatment of mucormycosis__
<br>2nd Henry Schuler Symposium on Mucormycosis, Chicago, IL USA

__Triazole Interactions with FLT3 inhibitors__
<br> 9th Trends in Medical Mycology Nice, France

__Echinocandin dosing, can we do better?__
<br> 9th Trends in Medical Mycology Nice, France

__How will targeted therapies in hematological disease change the management of fungal infections?__ 
<br> 55th Annual British Society Medical Mycology Meeting, Sheffield, United Kingdom

`2018`
__How to manage antimicrobial pharmacokinetic variability in the critically-ill patient__
<br> The European Society of Intensive Care Medicine (ESICM) Infections in ICU: Modern Management Fellowship Program: Modena, Italy

__PK/PD issues in septic shock__
<br> Antimicrobial Therapy in Immunocompromised and Critically Ill Patients: Management and Perspectives (ATCIP), Lugano, Switzerland	

__Debate-Are polyenes still relevant in 2018?__
<br> 20° Immunocompromised Host Society Meeting, Athens, Greece

__Optimizing antimicrobial pharmacokinetics in the ICU patient__
<br> 20° Immunocompromised Host Society Meeting, Athens, Greece	

__Pro-Con Debate “Con: Antifungal MICs are not as useful as you think with Cornelia Lass-Florl__
<br> 27th European Congress of Clinical Microbiology and Infectious Diseases (ECCMID), Madrid, Spain	 

__Principles of antifungal therapy, Principles of antibiotic therapy__
<br> Hematology resident Seminar. L'Istituto di Ematologia “Seràgnoli” Bologna. Italy

__The role of CT pulmonary angiography for the diagnosis of invasive mold disease__ 
<br> 54th Annual British Society Medical Mycology Meeting, Bristol, United Kingdom

__Can we improve the management of invasive mold disease using CT pulmonary angiography?__ 
<br> Infectious Diseases Grand Rounds, Centre hospitalier universitaire Vaudois (CHUV),Lausanne, Switzerland

__The Antifungal Pipeline__ 
<br> La micologia del III millennio – 2° edizione. Pescara, Italy

`2017` 
__How to manage antimicrobial pharmacokinetic variability in the critically-ill patient__ 
<br> The European Society of Intensive Care Medicine (ESICM) Infections in ICU: Modern Management Fellowship Program. Modena, Italy

__Immunopharmacology of antifungal therapy__ 
<br> Gilead Immunology Forum, Frankfurt, Germany

__Clinical considerations for the selection of antifungal therapy__ 
<br> Breaking the Mould Meeting. London, UK

__Radiological diagnostics in neutropenic and non-neutropenic patients__
<br> Joint annual Meeting of the Swiss Societies for Microbiology, Infectious Diseases, Hospital Hygiene, Tropical Medicine and Parasitology, and Tropical and Travel Medicine (SSI, SSHH, SSTMP, SSTTM). Basel, Switzerland.

__Antifungals and kidney Injury__ 
<br> 9° Congresso Nazionale DiTMO 2017. Geneva, Italy

__New Therapeutics for mucormycosis__ 
<br> 27th European Congress of Clinical Microbiology and Infectious Diseases (ECCMID). Vienna, Austria

__Differentiating fungal versus non-fungal pathology by CT imaging__
<br> Fungal Infection Update Meeting. London, UK

`2016`
__Antifungal pharmacology in the CNS__ 
<br> Gilead CARE Meeting, Munich, Germany

__Antifungal therapy update__ 
<br> S.Orsola-Malpighi Open Days Symposium, Bologna, Italy

__Farmacocinetica degli immunosopressor__
<br> Gruppo Italiano per il Trapianto di Midollo Osseo (GITMO) Cagliari, Italy

__Farmacocinetica degli antifungin__ 
<br> Gruppo Italiano per il Trapianto di Midollo Osseo (GITMO) Cagliari, Italy

__Pharmacokinetics and pharmacodyanamics of antifungals__ 
<br> New Perspectives in the Treatment of Invasive Fungal Infections Meeting, Bologna, Italy

__How to optimize liposomal amphotericin B dosing__
<br> Breaking the Mould Meeting, London, United Kingdom

__Controversies in antifungal therapy__
<br> Gruppo Italiano per il Trapianto di Midollo Osseo (GITMO), Bologna, Italy 

__Targeting fungal infections in the CNS-A summary of in vitro and in vivo experience__
<br> INFORM Meeting, Dubai, UAE

__Update on antifungal therapeutics__ 
<br> Mycology Update 2016, Parma, Italy

__Beyond direct antifungal activity-The immunomodulatory effect of echinocandin antifungals__
<br> 26th European Congress of Clinical Microbiology and Infectious Diseases (ECCMID), Amsterdam, Netherlands

__Antifungal therapeutic drug monitoring-Pro/Con debate: “PRO: When we should recommend TDM.__ 
<br> European Bone Marrow Transplantation (EBMT) Annual Meeting, Valencia, Spain

__Significant papers in infectious diseases__
<br> Update on the American Society of Hematology Meeting (Post-ASH). Genova, Italy

__Antifungal stewardship performance indicators and assessment__
<br> Transdisciplinary ECMM Antifungal Stewardship Workshop, Wesel, Germany

`2015`
__Antifungal stewardship in hematology units__ 
<br> Italy & Spain Friendship and opinions about antimicrobial stewardship programs. Bologna, Italy

__Reevaluating the role of liposomal amphotericin B in the treatment of life-threatening fungal diseases__
<br> Breaking the Mould Symposium” London, United Kingdom

__Optimizing antifungal dosing__ 
<br> Ankara Infectious Diseases Symposium, Ankara, Turkey

__Optimizing Antifungal Dosing__
<br> Turkish Society of Haematology, Istanbul, Turkey

__Do we routinely underdose antifungal therapy?__
<br> Izmir Infectious Diseases Symposium, Izmir, Turkey

__Antimicrobial Susceptibility Testing-A view from the pharmacologist__
<br> XI Corso Avanzato Di Terapia Antibiotica Pisa, Italy

`2014`
__Safety and toxicity of antifungal therapy__
<br> Infezioni fungine nel trapianto di organo solido: un anno dopo. Bologna, Italy

__Risk Models for Invasive Fungal Disease__ 
<br> 54th Interscience Conference on Antimicrobial Agents and Chemotherapy, Washington, DC, USA

__Optimizing antimicrobial therapy in the critically-ill-__
<br> Sepsi: Certezze Controversie nella diagnosi e nella gestion, Forli, Italy

__Antimicrobial pharmacokinetics and dynamics in the critically-ill__
<br> Stage Formativo. Società Italiana di Malattie Infettive e Tropicali (SIMIT). Bologna, Italy

__Antifungal penetration into difficult sites__
<br> 18th Biennial Symposium of the Immunocompromised Host Society (ICHS), Berlin, Germany

__Management of MDR organisms__
<br> 18th Biennial Symposium of the Immunocompromised Host Society (ICHS), Berlin, Germany

__Risk-Assessment for invasive mold diseases__
<br> 18th Biennial Symposium of the Immunocompromised Host Society (ICHS), Berlin, Germany

__Key strategies for managing breakthrough fungal infections__
<br> Paul Ehrlich Society for Chemotherapy-Spring Mycoses Meetings, Bonn, Germany

__Filling the gaps-New tools to identify invasive mold disease in hematology patients__
<br> Visiting Professor Grand Rounds, Infectious Diseases, University of Cologne, Cologne Germany

__Drug interactions and tolerability of triazoles__ 
<br> 6th Advances Against Aspergillus Conference, Madrid, Spain

`2013`
__Antimicrobial susceptibility testing-A view from the pharmacologist__
<br> X Corso Avanzato Di Terapia Antibiotica, Pisa, Italy

__PK:PD For the clinician-A 4 part lecture series__
<br> Invited Professor, Infectious Diseases Unit, University of Modena Modena, Italy

__Interazioni farmacologiche fra antifungini e farmaci antirigett__
<br> Infezioni fungine nel trapianto di organo solido: esperienze a confronto, Bologna, Italy

__PK:PD driven choice of antimicrobials in abdominal sepsis__
<br> Il Rischio infettivo in chirurgia addominale, Bologna, Italy

__Combination antifungal therapy-bench to bedside__
<br> 7th International Transplant Infectious Diseases Conference, Vienna, Austria

__Clinical Case- Voriconazole associated photoxicity__
<br> 7th International Transplant Infectious Diseases Conference, Vienna, Austria

__Antimicrobial pharmacokinetics and dynamics in the Critically-Ill__
<br> Stage Formativo. Società Italiana di Malattie Infettive e Tropicali (SIMIT). Bologna, Italy

__Risk model for invasive mold disease in hematology patient__
<br> Fungal Diseases in Hematology: Translating Basic Science into Clinical Practice. Parma, Italy

__Fungal meningitis outbreak in the United States__
<br> 7° Congresso Nazionale DiTMO - Diagnostica E Terapia Delle Micosi Oppotuniche Genoa, Italy

__Antimicrobial pharmacokinetics and dynamics in the critically-ill__
<br> Stage Formativo. Società Italiana di Malettie Infettive e Tropicali (SIMIT).  Bologna, Italy

__Overview of animal models of mucormycosis__ 
<br> ISHAM Zygomyctes workshop April, 2013, Utrecht, Netherlands

`2012`
__Optimizing antifungal therapy through pharmacokinetic/pharmacodynamics principles__ 
<br> Infectious Diseases Society of Portugal, Lisbon, Portugal

__Using pharmacodynamics to set antifungal susceptibility breakpoints__
<br> 52nd Interscience Conference on Antimicrobial Agents and Chemotherapy, San Francisco, California, USA

__Treatment of MDR P. aeruginosa and A. baumanii infections.__
<br> 17th International Symposium on Infections in Immunocompromised Hosts. Genoa, Italy

__Dose escalation strategies of liposomal amphotericin B in the treatment of experimental Aspergillus terreus pneumonia.__
<br> 18th Congress on the International Society for Human and Animal Mycology, Berlin, Germany

__Antimicrobial pharmacokinetics and dynamics in the critically-ill__
<br> Stage Formativo. Società Italiana di Malettie Infettive e Tropicali (SIMIT). Bologna, Italy

`2011`
__Is Antifungal susceptibility testing necessary in the Mmnagement of invasive candidiasis?__
<br> Pro-Con Debate. 49th Infectious Diseases Society of America Annual Meeting, Boston, Massachusetts, USA

__Overview of antifungal pharmacology__
<br> Sabati Ematologici della Romagna, Meldola, Italy 

__Overview of the immunopharmacological mechanisms of antifungals__ 
<br> Aggionarmenti in Terapia Antifungina: La Parola Agli Esperti, Bologna, Italy

`2010`
__Optimized antifungal prophylaxis in the high-risk patient__
<br> 45th Annual Midyear Meeting of the American Society for Health System Pharmacy, Anaheim, California

__Managing drug interactions with immunosuppressant agents__
<br>Infectious Diseases Society of America (IDSA) 48th Annual Meeting, Vancouver, Canada

__Challenging cases in antifungal therapeutic drug monitoring__ 
<br>Infectious Diseases Society of America (IDSA) 48th Annual Meeting, Vancouver, Canada

__The interplay of innate immunity and antifungal resistance__
<br> Astellas Pharmaceutical Global Advisory, Vancouver, Canada

__Triazole antifungal pharmacokinetics and pharmacodynamics__ 
<br> CE program, Boston, Massachusetts

__Update on the management of invasive fungal infections__
<br> University of Illinois-Chicago Infectious Diseases CME Symposium, Chicago, Illinois

__The ins and outs of scientific publication__
<br> Harris County Hospital Resident and Faculty Development Series, Houston, Texas

__Aspergillus, steroids and antifungals- What every patient should know__
<br> 3rd Advances Against Aspergillus Meeting, Rome, Italy

__Antibiotic Resistance Concerns in the Gyn-Onc Patient-__
<br> Gynecology-Oncology Grand Rounds. The University of Texas M.D. Anderson Cancer Center, Houston, Texas

__How does antifungal pharmacology differ for mucormycosis vs. aspergillosis?__
<br> Henry Schuler Memorial Symposium. Chicago, Illinois

__Managing antifungal nephrotoxicity and hepatotoxicity__
<br> 47th Meeting of the Infectious Diseases Society of America, Philadelphia, Pennsylvania

__Managing cytomegalovirus infections in transplant patients__ 
<br> Hematology Oncology Pharmacist Association (HOPA) CME webinar (Virtual)

__Getting with the Guidelines- Management of Invasive Candidiasis__
<br> CME Lecture Series provided in Philadelphia, Pennsylvania; Denver Colorado, San Jose, California and Los Angeles, California.

__Controversies and questions surrounding the antifungal formulary__
<br> Teleconference CME series. Broadlane Pharmacy Management Group, Houston, Texas

`2009`
__Where are the new antibiotics?__
<br> University of Houston College of Pharmacy Infectious Diseases Pharmacy CE Symposium, Houston, Texas

__Pharmacokinetic-pharmacodynamic optimization of antimicrobial dosing in the neutropenic patient__
<br> 17th Annual King Hussein Cancer Center Conference, Amman, Jordan

__New antimicrobials for neutropenic fever__
<br> 17th Annual King Hussein Cancer Center Conference, Amman, Jordan

__Controversies in the management of invasive candidiasis__
<br> Society of Hospital Medicine 2009 Annual Meeting, Chicago, Illinois

__Key pharmacological concerns in the management of invasive fungal infections__
<br> Visiting Professor- Case Discussions of Difficult Cases of Invasive Fungal Infections 
<br> Peking Medical University and College of Pharmacy, Beijing, China

__Intrapulmonary drug delivery and interactions with host cells__
<br> 4th Trends In Medical Mycology (TIMM) Annual Meeting, Athens, Greece

__New antimicrobials and antibiotic dosing strategies in neutropenic fever-__
<br> Hematologic Malignancies Conference 2009. Brussels, Belgium

__Controversies in the management of invasive candidiasis__
<br> 5th Annual Infectious Diseases- Critical Care Pharmacy CE Conference, Toronto, Ontario, Canada

`2008`
__Improving the pharmacology of invasive mould infections__
<br> Infectious Diseases Grand Rounds, Memorial Sloan-Kettering Cancer Center, New York, New York

__Evidence versus pragmatism in managing invasive candidiasis__
<br> Infectious Diseases Grand Rounds, University of Nebraska Medical Center, Omaha, Nebraska

__Cases in antifungal therapeutic drug monitoring__ 
<br> Houston Infectious Diseases Pharmacy Network. Houston, Texas

`2007`
__The case for fluconazole as front-line therapy in invasive candidiasis: Pro-con debate__
<br> American Society of Heath-System Pharmacy Annual Meeting, Las Vegas, Nevada

__Systemic antifungal therapy-What every clinician should know__
<br> American Society of Heath-System Pharmacy Annual Meeting, Las Vegas, Nevada

__Interpreting antifungal susceptibility testing__
<br>47th Interescience Conference on Antimicrobial Agents and Chemotherapy, Chicago, Illinois

__Salvage antifungal therapy, Combination therapy, and Antifungal pharmacodynamics__
<br> AB Biodisk ABLE Course, Stockholm Sweden

__Antifungal therapeutic drug monitoring-__
<br> Pharmacy Grand Rounds, Memorial Sloan-Kettering Cancer Center, New York, New York

__What are the real differences between the echinocandins?__ 
<br> Department of Hematology and Transplantation. Oregon Health Sciences Center, Portland, Oregon

__Managing infections in the immunocompromised host__
<br> Hematology Oncology Pharmacist Association (HOPA) Annual Meeting. Denver, Colorado

`2006`
__The new antifungal formulary__
<br> City of Hope Pharmacotherapy Symposium. Anaheim, California

__Antifungal pharmacodynamics- A focus on the echinocandins-__
<br> 17th European Conference on Chemotherapy, Microbiology and Infectious Diseases. Munich, Germany

__Antifungal therapeutic drug monitoring__ 
<br> Blood and Marrow Transplantation Case Conference. M.D. Anderson Cancer Center, Houston, Texas

__Making sense of the antifungal formulary__ 
<br> Malaysian Society of Hematology Conference, Kuala Lumpur, Malaysia

__Role of new antifungal agents in the management of invasive fungal infections__
<br> Hematology Grand Rounds. Hong Kong Sanatorium Hospital. Hong Kong, China

__New drugs and new opportunities for combination antifungal therapy__
<br> Grand Rounds. Queen Mary Hospital. Hong Kong, China

__Role of new antifungal agents in the management of invasive fungal infections__ 
<br> City Hematology Conference. Beijing China 

__Role of new antifungal agents in the management of invasive fungal infections__ 
<br> Infectious Diseases Citywide Conference, Shanghai, China

__Antifungal therapy-Consensus and controversy__
<br> UCSF Medical Center Pharmacy Forum. San Francisco, California

__Invasive fungal infection-consensus and controversies__
<br> UCLA Infectious Diseases Grand Rounds, Los Angeles, California

__Management of invasive fungal infections-the MDACC approach__
<br>ABLE Susceptibility Course, Stockholm, Sweden

__Antifungal formulary 2006__
<br> Tennessee ACCP Summer Chapter Meeting. Memphis, Tennessee

__Antifungal formulary 2006__
<br> St. Jude’s Children’s Hospital, Memphis, Tennessee

__Antifungal controversies 2006-__
<br> Vanderbilt Department of Infectious Diseases, Nashville, Tennessee

__Conundrums of testing antifungal combinations in the laboratory__ 
<br> International Society of Human and Animal Mycology Congress, Paris, France

__Difficulties in establishing in vitro/in vivo correlations with antifungal activity__
<br> International Society of Human and Animal Mycology Congress, Paris, France

__Antifungal formulary 2006__
<br> Oregon Health Sciences Center. Department of Infectious Diseases, Portland, Oregon

__Antifungal formulary-Best picks-__
<br> University of Houston College of Pharmacy Infectious Diseases CE Symposium, Houston, Texas

__Do we routinely underdose antifungal therapy?__
<br> British Society for Medical Mycology Annual Meeting, Clontarf Castle, Dublin, Ireland

__Managing drug interactions in the patient with aspergillosis__
<br> 2nd Annual Advances Against Aspergillosis Meeting, Athens Greece

__Overview of antifungal pharmacology__
<br> Frontline CE Symposium. Houston, Texas

`2005`
__Drosophila as a high-throughput model for studying fungal pathogenesis-__
<br> Texas-UK Biosciences Research Collaborative, London School of Tropical Health and Hygiene, London, United Kingdom

__Antifungal Susceptibility to guide empiric therapy and combination therapy__
<br> AB Biodisk Antifungal Susceptibility Course, Stockholm, Sweden

__Quinolone-associated MRSA-Significant papers in infectious diseases__
<br> American College of Clinical Pharmacy Annual Meeting, San Francisco, California

__Decisions concerning the use of combination antifungal therapy__
<br> American College of Clinical Pharmacy Annual Meeting, San Francisco, California

__Neutrophil subsets and infection-New insights into “adaptable” innate immunity__
<br> MD. Anderson Infectious Diseases Grand Rounds

__Management of infection in the immunocompromised host__ 
<br> Merck Acute Care Sales Force National Training Symposium Jacksonville, Florida

__Combination antifungal therapy-Pro vs. Con-__
<br> North Carolina Chapter of the American College of Clinical Pharmacy, Durham, North Carolina

__New antifungals, New treatment options__
<br> Louisiana State University Charity Hospital Infectious Diseases Grand Rounds

__New frontiers in the treatment of invasive fungal infections-__
<br> Making a Difference Pharmacy CE Conference, Carefree, Arizona 

__New frontiers in the treatment of invasive fungal infections-__
<br>Alabama Society of Health-System Pharmacists Annual Meeting, San Destin, Florida

__New frontiers in the treatment of invasive fungal infections-__
<br>New Orleans Society of Health System Pharmacists, New Orleans, Louisiana

__Do we routinely under-dose antifungal therapy?__
<br> National Institute of Allergy and Infectious Diseases Grand Rounds, National Institutes of Health, Bethesda, Maryland

__Toxigenic moulds in Texas: New insights into the pathogenesis of an opportunistic pathogen__
<br> The University of Tennessee College of Pharmacy, Memphis, TN

`2004`
__Practical management of multidrug resistant infections__
<br> Session moderator. ASHP Annual Meeting, Orlando, Florida

__Evidence surrounding consensus recommendations for monitoring of serum vancomycin levels__
<br> ASHP Annual Meeting, Orlando, Florida

__Case studies in the selection of antifungal therapy__
<br> Division of Infectious Diseases, Henry Ford Hospital, Detroit, Michigan

__Immunology of effective antifungal therapy__
<br> Wayne State College of Pharmacy, Detroit, Michigan

__Overview of antifungal pharmacology, antifungal resistance, Combination antifungal therapy__
<br> AB Biodisk Antifungal Susceptibility Course, Stockholm, Sweden

__Pharmacotherapy of invasive fungal infections__
<br>University of Connecticut School of Pharmacy ID Symposium, Storrs, Conneticut

__Treatment of fungal infection in the ICU patient__
<br> New England Critical Care Pharmacy Symposium. Newton, Massachusetts

__Newer antifungal therapies and their role in the therapy of invasive mycoses__ 
 <br>Pharmacy Society of Wisconsin Annual Meeting. Madison, Wisconsin
 
__New antibiotics for the perfect storm of infectious diseases__
<br> Texas Society of Health Systems Annual Meeting. Houston, Texas

`2003`
__Antifungal therapy and Evedence-based medicine__
<br> ASHP Annual Meeting, New Orleans, Louisiana

__The perfect storm in infectious diseases__
<br> ASHP Section of Clinical Specialists and Scientist Network Assembly. Moderator. ASHP Annual Meeting, New Orleans, Louisiana

__Antibiotic selection in gynecology-oncology patient__
<br> Gynecology-Oncology Grand Rounds. The University of Texas M.D. Anderson Cancer Center, Houston, TX

__Significant papers in pharmacotherapy—SARS__
<br> American College of Clinical Pharmacy Annual Meeting, Atlanta, Georgia

__Menacing moulds and new antifungals__
<br> Gulf Coast Society of Health-System Pharmacists, Houston, Texas

__Antifungal therapy consideration in the transplant patient__
<br> Good Samaritan Hospital, Phoenix, Arizona

__Antifungal resistance-Is the fluconazole era over?__
<br> University of Missouri-Kansas City Infectious Diseases Symposium

__Antifungal resistance__
<br> Oklahoma Society of Health System Pharmacist Annual Meeting, Oklahoma City, Oklahoma

__Pharmacotherapy of invasive candidiasis__
<br> Citywide Pharmacy CE Conference. Denver, Colorado

__Invasive candidiasis__
<br> St. Lukes Hospital, Houston, Texas

__Menacing moulds__ 
<br> Great Lakes CE Conference. Grand Rapids, Michigan

__Echinocandins and Lipid AMB formulations__ 
<br> Mycoses 2002 Symposia (given with Drs. Gerald Bodey, Dimitrios Kontoyiannis, and Issam Raad), Houston, Texas

`2002`
__Beyond Microdilution Broth Antifungal Susceptibility Testing__ 
<br> Pre-symposium to the 41st, 42nd and 44th Interscience Conference on Antimicrobial Agents and Chemotherapy, Antifungal Susceptibility Testing for the Clinician. San Diego, California, Chicago, Illinois, and Washington, D.C

__Respiratory Infection Update__
<br> Texas Academy of Family Practice Physicians- Fall CME Symposium, Houston, Texas

__Management of Invasive Fungal Infections in the Critically Ill Patient__
<br> Infectious Disease Pharmacotherapy CE Symposium, San Antonio, Texas

__New Agents and Evolving Strategies for Life-Threatening Fungal Infections in the Immunocompromised Patients__ 
<br> The 24th Annual M.D. Anderson Cancer Center Pharmacy Symposium on Cancer Chemotherapy. Houston, Texas

__Controversies in Antifungal Pharmacology__
<br> Citywide ID conference. Seattle, Washington

__Is Immunodysregulation a Virulence Factor for Aspergillus?__
<br> Houston Area Mycoses Study Group. The University of Texas M.D. Anderson Cancer Center, Houston, Texas

__The Immunology of Effective Antifungal Therapy__
<br> M.D. Anderson Cancer Center Infectious Diseases Research Conference, Houston Texas

`2001`
__New antifungal formulations, new antifungal targets__
<br> Grand Rounds, Fairfax Hospital, Fairfax, Virginia 
<br> Baylor Medical Center, Dallas, Texas
<br> Texas Society of Health System Pharmacists, Annual Meeting Austin, Texas
<br> Kentucky Society of Health System Pharmacists, Annual Meeting Louisville, Kentucky
<br> Infectious Diseases Pharmacy Symposium, Albuquerque, New Mexico
<br> Infectious Diseases Citywide Symposium, Phoenix, Arizona
<br> Oklahoma Society of Health System Pharmacists, Tulsa Oklahoma

__The Dilemma of Defining Optimal Treatment Strategies for Refractory Mycoses__
<br> 2001 American College of Clinical Pharmacy Meeting, Tampa, Florida

__New antibiotic update-__
<br> Ft. Bend Physician Medical Society, Sugarland, Texas

__Pharmacology of Current and Future Antifungals__
<br> Infectious Diseases Morning Rounds, Barnes-Jewish Hospital at Washington University Medical Center, St. Louis, Missouri

__Pharmacology of Current and Future Antifungals__
<br> Mycoses 2001 (with Drs. John Rex, Richard Hamill, and Dimitrios Kontoyiannis), Houston, Texas

`2000`
__New Antimicrobials for Resistant Gram-Positive Infections__
<br> Parkland Medical Center Infectious Diseases Dallas, Texas

__What is Considered Broad-Spectrum Therapy? A re-examination of the ATS Guidelines for nosocomial pneumonia__
<br> Memorial Southwest Hospital (Baylor) Grand Rounds, Houston, Texas

__Controversies in the Management of Invasive Fungal Infections__
<br> Southwestern Med. School Infectious Diseases Grand Rounds, Dallas, Texas
<br> Grand Rounds, Wilford Hall Medical Center, San Antonio, Texas
<br> Clinical Updates 2000- Annual Meeting of the California Society of Health System Pharmacists, Palm Springs, California
<br> Winter CE meeting of the Southern Colorado Society of Health System Pharmacists, Colorado Springs, Colorado
<br> Grand Rounds, Memorial Southeast Medical Center, Houston, Texas

__New Antimicrobials for the Post-Antibiotic Era__
<br> UH Infectious Diseases Continuing Education Symposium, Texas Medical Center Marriott Hotel, Houston, Texas

__Are We Nearing the End of the Fluconazole Era?__ 
<br> Advances in Oncology Institutional Grand Rounds. M.D. Anderson Cancer Center (Given with Drs. Gerald Bodey and Issam Raad). Houston, Texas

__Antifungal Pharmacodynamics__
<br> M.D. Anderson Infectious Diseases Research Conference, Houston Texas

__Differentiating the Quinolones-Do we really need new agents?__
<br> Resident Grand Rounds, Corpus Christi, Texas
<br> Houston Area Society of Otolaryngologists, Houston, Texas.

__Implications of streptococcal resistance for antibiotic therapy__
<br> Border Issues and Resistance, University of Texas CME Otolaryngology Conference. McAllen, Texas

`1999`
__Antifungal Pharmacodynamics-What Emerging Data Are Telling Us About Dosing Antifungal Therapy__
<br> Visiting Professor Series; Department of Pharmacological and Pharmaceutical Sciences. University of Houston College of Pharmacy. Houston, Texas

__Should Combinations of Amphotericin B and Fluconazole Be Used for the Treatment of Candidemia?__ 
<br> University of Wisconsin College of Pharmacy, Madison, Wisconsin

`1998`
__IDSA Guidelines for the Treatment of Community Acquired Pneumonia:Resistant S. pneumoniae and the Role of Quinolones__
<br> Fellowship Forum. University of Iowa, Iowa City, Iowa

`1997`
__Pharmacodynamic Evaluation of Combination Amphotericin B-Fluconazole Activity Using an In Vitro Infection Model__
<br> Fellow Seminar Series. University of Iowa. Iowa City, Iowa

__Evolving Role of Oral Antimicrobial Therapy-__
<br> Pulmonology Conference Series. Barnes-Jewish Hospital. Washington University Medical School.
St. Louis, Missouri

__Evaluation of Colony Stimulating Factor Use in a Large Teaching Hospital__
<br> Midwest Residency Conference, Memphis, Tennessee

`1996`
__Colony Stimulating Factors as Adjunctive Treatment in Acute Myelogenous Leukemia__
<br> Residency Seminar Series. St. Louis, Missouri

__Rational Use of Step-Down Oral Antibiotic Therapy-__
<br> Pharmacists Continuing Education. Barnes- Jewish Hospital, St. Louis, Missouri

`1995`
__Continuous infusion loop diuretics to overcome diuretic resistance__ 
<br>Doctor of Pharmacy Seminar. University of Kansas Medical Center, Kansas City, Kansas


## Publications

__Scopus author ID: 7404846664 <br>
314 peer-reviewed publications, H index 77, 18,686 citations__ <br>

1. Lewis RE, Stanzani M, Morana G, Sassi C. Radiology-based diagnosis of fungal pulmonary infections in high-risk hematology patients: are we making progress? Current Opinion Infectious Diseases. 2023:36:250-256.

1. Bartoletti, M Antonelli, A Bussini, L Corcione, S Giacobbe, DR Marconi, L Pascale, R Dettori, S Shbaklo, N Ambretti, S Gaibani, P Giani, T Coppi, M Bassetti, M De Rosa, FG Marchese, A Cavallo, R Lewis, R Rossolini, GM Viale, P Giannella, M. Clinical consequences of very major errors with semi-automated testing systems for antimicrobial susceptibility of carbapenem-resistant Enterobacterales. Clinical Microbiology and Infections Diseases 2022;8:1290.e1 - 1290.e4.

1. Lamoth F, Lewis RE, Kontoyiannis DP. Investigational agents for invasive mycoses: A clinical perspective. Clinical Infectious Diseases 2022;75:534-544.

1. Stemler J, de Jonge N, Skoetz N, Sinkó J, Brüggemann RJ, Busca A, Ben-Ami R, Racil Z, Piechotta V, Lewis R, Cornely OA. Antifungal prophylaxis in adult patients with acute myeloid leukaemia treated with novel targeted therapies: EHA recommendations. The Lancet Haematology 2022;9:e361-e373.

1. Brüggemann RJ, Verheggen R, Boerrigter E, Stanzani M, Verweij PE, Blijlevens NMA, Lewis RE. Management of drug–drug interactions of targeted therapies for haematological malignancies and triazole antifungal drugs. The Lancet Haematology. 2022;9(1):e58–72.

2. Verweij PE, Brüggemann RJM, Azoulay E, Bassetti M, Blot S, Buil JB, Calandra T, Chiller T, Clancy CJ, Cornely OA, Depuydt P, Koehler P, Lagrou K, de Lange D, Lass-Flörl C, Lewis RE, Lortholary O, Liu P-WL, Maertens J, Nguyen MH, Patterson TF, Rijnders BJA, Rodriguez A, Rogers TR, Schouten JA, Wauters J, van de Veerdonk FL, Martin-Loeches I. Taskforce report on the diagnosis and clinical management of COVID-19 associated pulmonary aspergillosis. Intensive Care Medicine. 2021;47(8):819–34\.

3. Stanzani M, Sassi C, Lewis R, Sartor C, Rasetto G, Cavo M, Battista G. Early low-dose computed tomography with pulmonary angiography to improve the early diagnosis of invasive mould disease in patients with haematological malignancies: A pilot study. Journal of Infection. 2021;83(3):371–80\.

4. Rinaldi M, Bartoletti M, Ferrarese A, Franceschini E, Campoli C, Coladonato S, Pascale R, Tedeschi S, Gatti M, Cricca M, Ambretti S, Siniscalchi A, Morelli MC, Cescon M, Cillo U, Di Benedetto F, Burra P, Mussini C, Cristini F, Lewis R, Viale P, Giannella M. Breakthrough invasive fungal infection after liver transplantation in patients on targeted antifungal prophylaxis: A prospective multicentre study. Transplant Infectious Disease [Internet]. 2021;23(4).

5. Pascale R, Bussini L, Gaibani P, Bovo F, Fornaro G, Lombardo D, Ambretti S, Pensalfine G, Appolloni L, Bartoletti M, Tedeschi S, Tumietto F, Lewis R, Viale P, Giannella M. Carbapenem resistant bacteria in Intensive Care Unit during COVID-19 pandemic: Multicenter before-after cross sectional study. Infection Control and Hospital Epidemiology. 2021

7. Lamoth F, Lewis RE, Kontoyiannis DP. Navigating the uncertainties of COVID-19–associated aspergillosis: A Comparison With influenza-associated aspergillosis. Journal of Infections Diseases. 2021;224:1631-1640.

6. Lewis RE, Andes DR. Managing uncertainty in antifungal dosing: antibiograms, therapeutic drug monitoring and drug-drug interactions. Current Opinion in Infectious Diseases. 2021;34(4):288–96.

7. Lamoth F, Lewis RE, Kontoyiannis DP. Role and interpretation of antifungal susceptibility testing for the management of invasive fungal infections. Journal of Fungi. 2021;7(1):1–21.

8. Johnson MD, Lewis RE, Dodds Ashley ES, Perfect JR, Kontoyiannis DP. Reply to Day et al. Journal of Infectious Diseases. 2021;224(9):1627–8.

9. Gudiol C, Lewis RE, Strati P, Kontoyiannis DP. Chimeric antigen receptor T-cell therapy for the treatment of lymphoid malignancies: is there an excess risk for infection? The Lancet Haematology. 2021;8(3):e216–28.

10. Glampedakis E, Cassaing S, Fekkar A, Dannaoui E, Bougnoux M-E, Bretagne S, Neofytos D, Schreiber PW, Hennequin C, Morio F, Shadrivova O, Bongomin F, Fernández-Ruiz M, Bellanger AP, Arikan-Akdagli S, Erard V, Aigner M, Paolucci M, Khanna N, Charpentier E, Bonnal C, Brun S, Gabriel F, Riat A, Zbinden R, Le Pape P, Klimko N, Lewis RE, Richardson M, İnkaya AC, Coste AT, Bochud P-Y, Lamoth F. Invasive aspergillosis due to aspergillus section usti: A multicenter retrospective study. Clinical Infectious Diseases. 2021;72(8):1379–85.

11. Giannella M, Freire M, Rinaldi M, Abdala E, Rubin A, Mularoni A, Gruttadauria S, Grossi P, Shbaklo N, Tandoi F, Ferrarese A, Burra P, Fernandes R, Aranha Camargo LF, Asensio A, Alagna L, Bandera A, Simkins J, Abbo L, Halpern M, Santana Girao E, Valerio M, Muñoz P, Fernandez Yunquera A, Statlender L, Yahav D, Franceschini E, Graziano E, Morelli MC, Cescon M, Viale P, Lewis R, Bartoletti M, Pascale R, Campoli C, Coladonato S, Cristini F, Tumietto F, Siniscalchi A, Laici C, Ambretti S, Romagnoli R, De Rosa FG, Muscatello A, Mangioni D, Gori A, Antonelli B, Dondossola D, Rossi G, Invernizzi F, Peghin M, Cillo U, Mussini C, Benedetto FD, Terrabuio DRB, Bittante CD, Toniolo ADR, Balbi E, Garcia JHP, Morrás I, Ramos A, Cruz AF, Salcedo M. Development of a risk prediction model for carbapenem-resistant enterobacteriaceae infection after liver transplantation: A multinational cohort study. Clinical Infectious Diseases. 2021;73(4):E955–66.

12. Gaibani P, Viciani E, Bartoletti M, Lewis RE, Tonetti T, Lombardo D, Castagnetti A, Bovo F, Horna CS, Ranieri M, Viale P, Re MC, Ambretti S. The lower respiratory tract microbiome of critically ill patients with COVID-19\. Scientific Reports [Internet]. 2021;11(1).

13. Bartoletti M, Pascale R, Cricca M, Rinaldi M, Maccaro A, Bussini L, Fornaro G, Tonetti T, Pizzilli G, Francalanci E, Giuntoli L, Rubin A, Moroni A, Ambretti S, Trapani F, Vatamanu O, Ranieri VM, Castelli A, Baiocchi M, Lewis R, Giannella M, Viale P. Epidemiology of invasive pulmonary aspergillosis among intubated patients with COVID-19: A prospective study. Clinical Infectious Diseases. 2021;73(11):e3606–14\.

14. Axell-House DB, Wurster S, Jiang Y, Kyvernitakis A, Lewis RE, Tarrand JJ, Raad II, Kontoyiannis DP. Breakthrough mucormycosis developing on mucorales-active antifungals portrays a poor prognosis in patients with hematologic cancer. Journal of Fungi [Internet]. 2021;7(3).

15. Zaghi I, Gaibani P, Campoli C, Bartoletti M, Giannella M, Ambretti S, Viale P, Lewis RE. Serum bactericidal titres for monitoring antimicrobial therapy: current status and potential role in the management of multidrug-resistant Gram-negative infections. Clinical Microbiology and Infection. 2020;26(10):1338–44.

16. Verweij PE, Rijnders BJA, Brüggemann RJM, Azoulay E, Bassetti M, Blot S, Calandra T, Clancy CJ, Cornely OA, Chiller T, Depuydt P, Giacobbe DR, Janssen NAF, Kullberg B-J, Lagrou K, Lass-Flörl C, Lewis RE, Liu PW-L, Lortholary O, Maertens J, Martin-Loeches I, Nguyen MH, Patterson TF, Rogers TR, Schouten JA, Spriet I, Vanderbeke L, Wauters J, van de Veerdonk FL. Review of influenza-associated pulmonary aspergillosis in ICU patients and proposal for a case definition: an expert opinion. Intensive Care Medicine. 2020;46(8):1524–35.

17. Tolomelli G, Mancuso K, Tacchetti P, Patriarca F, Galli M, Pantani L, Zannetti B, Motta MR, Rizzi S, Dan E, Sinigaglia B, Giudice V, Olmo A, Arpinati M, Chirumbolo G, Fanin R, Lewis RE, Paris L, Bonifazi F, Cavo M, Curti A, Lemoli RM. The timing of plerixafor addition to G-Csf and chemotherapy affects immunological recovery after autologous stem cell transplant in multiple myeloma. Bone Marrow Transplantation. 2020;55(5):946–54.

18. Lewis RE, Kontoyiannis DP. Infectious disease consultation for candidaemia. The Lancet Infectious Diseases. 2020;20(2):164.

19. Lewis RE, Kontoyiannis DP. Chimeric antigen receptor T-cell immunotherapy and need for prophylaxis for invasive mold infections. Clinical Infectious Diseases. 2020;71(7):1802–3.

20. Johnson MD, Lewis RE, Dodds Ashley ES, Ostrosky-Zeichner L, Zaoutis T, Thompson GR, Andes DR, Walsh TJ, Pappas PG, Cornely OA, Perfect JR, Kontoyiannis DP. Core recommendations for antifungal stewardship: a statement of the mycoses study group education and research consortium. Journal of Infectious Diseases. 2020;222:S175–98.

21. Giannella M, Pascale R, Pancaldi L, Monari C, Ianniruberto S, Malosso P, Bussini L, Bartoletti M, Tedeschi S, Ambretti S, Lewis R, Viale P. Follow-up blood cultures are associated with improved outcome of patients with gram-negative bloodstream infections: retrospective observational cohort study. Clinical Microbiology and Infection. 2020;26(7):897–903.

22. Garcia-Vidal C, Lewis RE, Kontoyiannis DP. Combination antifungal therapy for breakthrough invasive mould disease in patients with haematological malignancies: When management reasoning eclipses evidence-based medicine. Journal of Antimicrobial Chemotherapy. 2020;75(11):3096–8.

23. Fernández-Cruz A, Lewis RE, Kontoyiannis DP. How long do we need to treat an invasive mold disease in hematology patients? factors influencing duration of therapy and future questions. Clinical Infectious Diseases. 2020;71(3):685–92.

24. Coppola PE, Gaibani P, Sartor C, Ambretti S, Lewis RE, Sassi C, Pignatti M, Paolini S, Curti A, Castagnetti F, Ursi M, Cavo M, Stanzani M. Ceftolozane-tazobactam treatment of hypervirulent multidrug resistant pseudomonas aeruginosa infections in neutropenic patients. Microorganisms. 2020;8(12):1–11.

25. Bartoletti M, Baldassarre M, Domenicali M, Lewis RE, Giannella M, Antognoli A, Rinaldi M, Zaccherini G, Verucchi G, Marconi L, Tamè M, Berardi S, Napoli L, Siniscalchi A, Fabbri A, Biselli M, Tufoni M, Pavarin RM, Trevisani F, Viale P, Bernardi M, Caraceni P. Prognostic role of bacterial and fungal infections in patients with liver cirrhosis with and without acute-on-chronic liver failure: A prospective 2-Center study. Open Forum Infectious Diseases [Internet]. 2020;7(11).

26. Zoran T, Sartori B, Sappl L, Aigner M, Sánchez-Reus F, Rezusta A, Chowdhary A, Taj-Aldeen SJ, Arendrup MC, Oliveri S, Kontoyiannis DP, Alastruey-Izquierdo A, Lagrou K, Lo Cascio G, Meis JF, Buzina W, Farina C, Drogari-Apiranthitou M, Grancini A, Tortorano AM, Willinger B, Hamprecht A, Johnson E, Klingspor L, Arsic-Arsenijevic V, Cornely OA, Meletiadis J, Prammer W, Tullio V, Vehreschild J-J, Trovato L, Lewis RE, Segal E, Rath P-M, Hamal P, Rodriguez-Iglesias M, Roilides E, Arikan-Akdagli S, Chakrabarti A, Colombo AL, Fernández MS, Martin-Gomez MT, Badali H, Petrikkos G, Klimko N, Heimann SM, Uzun O, Roudbary M, De La Fuente S, Houbraken J, Risslegger B, Sabino R, Lass-Flörl C, Lackner M. Corrigendum: Azole-resistance in aspergillus terreusand related species: An emerging problem or a rare phenomenon? Frontiers in Microbiology (2018) 9 (516).

27. Wurster S, Lewis RE, Albert ND, Kontoyiannis DP. Preexposure to isavuconazole increases the virulence of mucorales but not aspergillus fumigatus in a drosophila melanogaster infection model. Antimicrobial Agents and Chemotherapy [Internet]. 2019;63(2).

28. Wurster S, Kumaresan PR, Albert ND, Hauser PJ, Lewis RE, Kontoyiannis DP. Live monitoring and analysis of fungal growth, viability, and mycelial morphology using the incucyte neurotrack processing module. mBio [Internet]. 2019;10(3).

29. Welte T, Len O, Muñoz P, Romani L, Lewis R, Perrella A. Invasive mould infections in solid organ transplant patients: modifiers and indicators of disease and treatment response. Infection. 2019;47(6):919–27.

30. Walsh TJ, Lewis RE, Adler-Moore J. Pharmacology of liposomal amphotericin b: An introduction to preclinical and clinical advances for treatment of life-threatening invasive fungal infections. Clinical Infectious Diseases. 2019;68:S241–3.

31. Stanzani M, Vianelli N, Cavo M, Kontoyiannis DP, Lewis RE. Development and internal validation of a model for predicting 60-day risk of invasive mould disease in patients with haematological malignancies. Journal of Infection. 2019;78(6):484–90.

32. Stanzani M, Sassi C, Battista G, Lewis RE. Beyond biomarkers: How enhanced CT imaging can improve the diagnostic-driven management of invasive mould disease. Medical Mycology. 2019;57:S274–86.

33. Stanzani M, Cricca M, Sassi C, Sutto E, De Cicco G, Bonifazi F, Bertuzzi C, Bacci F, Paolini S, Cavo M, Lewis RE. Saprochaete clavata infections in patients undergoing treatment for haematological malignancies: A report of a monocentric outbreak and review of the literature. Mycoses. 2019;62(12):1100–7.

34. Lewis RE, Wurster S, Beyda ND, Albert ND, Kontoyiannis DP. Comparative in vitro pharmacodynamic analysis of isavuconazole, voriconazole, and posaconazole against clinical isolates of aspergillosis, mucormycosis, fusariosis, and phaeohyphomycosis. Diagnostic Microbiology and Infectious Disease [Internet]. 2019;95(3).

35. Lewis RE, Kontoyiannis DP, Viale P, Sarpong EM. Using state transition models to explore how the prevalence of subtherapeutic posaconazole exposures impacts the clinical utility of therapeutic drug monitoring for posaconazole tablets and oral suspension. Antimicrobial Agents and Chemotherapy [Internet]. 2019;63(12).

36. Groll AH, Rijnders BJA, Walsh TJ, Adler-Moore J, Lewis RE, Brüggemann RJM. Clinical pharmacokinetics, pharmacodynamics, safety and efficacy of liposomal amphotericin b. Clinical Infectious Diseases. 2019;68:S260–74.

37. Giannella M, Pascale R, Ferraro G, Toschi A, Pancaldi L, Furii F, Bartoletti M, Tedeschi S, Ambretti S, Lewis RE, Viale P. Risk factors for treatment failure in patients receiving β-lactam/β-lactamase inhibitor combinations for Enterobacteriaceae bloodstream infection: A retrospective, single-centre, cohort study. International Journal of Antimicrobial Agents. 2019;53(5):574–81.

38. Giannella M, Bussini L, Pascale R, Bartoletti M, Malagrinò M, Pancaldi L, Toschi A, Ferraro G, Marconi L, Ambretti S, Lewis R, Viale P. Prognostic utility of the new definition of difficult-to-treat resistance among patients with gram-negative bloodstream infections. Open Forum Infectious Diseases [Internet]. 2019;6(12).

39. Giannella M, Bartoletti M, Campoli C, Rinaldi M, Coladonato S, Pascale R, Tedeschi S, Ambretti S, Cristini F, Tumietto F, Siniscalchi A, Bertuzzo V, Morelli MC, Cescon M, Pinna AD, Lewis R, Viale P. The impact of carbapenemase-producing Enterobacteriaceae colonization on infection risk after liver transplantation: a prospective observational cohort study. Clinical Microbiology and Infection. 2019;25(12):1525–31.

40. Gaibani P, Lombardo D, Bartoletti M, Ambretti S, Campoli C, Giannella M, Tedeschi S, Conti M, Mancini R, Landini MP, Re MC, Viale P, Lewis RE. Comparative serum bactericidal activity of meropenem-based combination regimens against extended-spectrum beta-lactamase and KPC-producing Klebsiella pneumoniae. European Journal of Clinical Microbiology and Infectious Diseases. 2019;38(10):1925–31.

41. Cornely OA, Alastruey-Izquierdo A, Arenz D, Chen SCA, Dannaoui E, Hochhegger B, Hoenigl M, Jensen HE, Lagrou K, Lewis RE, Mellinghoff SC, Mer M, Pana ZD, Seidel D, Sheppard DC, Wahba R, Akova M, Alanio A, Al-Hatmi AMS, Arikan-Akdagli S, Badali H, Ben-Ami R, Bonifaz A, Bretagne S, Castagnola E, Chayakulkeeree M, Colombo AL, Corzo-León DE, Drgona L, Groll AH, Guinea J, Heussel C-P, Ibrahim AS, Kanj SS, Klimko N, Lackner M, Lamoth F, Lanternier F, Lass-Floerl C, Lee D-G, Lehrnbecher T, Lmimouni BE, Mares M, Maschmeyer G, Meis JF, Meletiadis J, Morrissey CO, Nucci M, Oladele R, Pagano L, Pasqualotto A, Patel A, Racil Z, Richardson M, Roilides E, Ruhnke M, Seyedmousavi S, Sidharthan N, Singh N, Sinko J, Skiada A, Slavin M, Soman R, Spellberg B, Steinbach W, Tan BH, Ullmann AJ, Vehreschild JJ, Vehreschild MJGT, Walsh TJ, White PL, Wiederhold NP, Zaoutis T, Chakrabarti A. Global guideline for the diagnosis and management of mucormycosis: an initiative of the European Confederation of Medical Mycology in cooperation with the Mycoses Study Group Education and Research Consortium. The Lancet Infectious Diseases. 2019;19(12):e405–21.

42. Bartoletti M, Giannella M, Lewis RE, Caraceni P, Tedeschi S, Paul M, Schramm C, Bruns T, Merli M, Cobos-Trigueros N, Seminari E, Retamar P, Muñoz P, Tumbarello M, Burra P, Cerenzia MT, Barsic B, Calbo E, Maraolo AE, Petrosillo N, Galan-Ladero MA, D’Offizi G, Zak-Doron Y, Rodriguez-Baño J, Baldassarre M, Verucchi G, Domenicali M, Bernardi M, Viale P. Extended infusion of β-lactams for bloodstream infection in patients with liver cirrhosis: An observational multicenter study. Clinical Infectious Diseases. 2019;69(10):1731–9.

43. Adler-Moore J, Lewis RE, Brüggemann RJM, Rijnders BJA, Groll AH, Walsh TJ. Preclinical safety, tolerability, pharmacokinetics, pharmacodynamics, and antifungal activity of liposomal amphotericin b. Clinical Infectious Diseases. 2019;68:S244–59.

44. Zoran T, Sartori B, Sappl L, Aigner M, Sánchez-Reus F, Rezusta A, Chowdhary A, Taj-Aldeen SJ, Arendrup MC, Oliveri S, Kontoyiannis DP, Alastruey-Izquierdo A, Lagrou K, Cascio GL, Meis JF, Buzina W, Farina C, Drogari-Apiranthitou M, Grancini A, Tortorano AM, Willinger B, Hamprecht A, Johnson E, Klingspor L, Arsic-Arsenijevic V, Cornely OA, Meletiadis J, Prammer W, Tullio V, Vehreschild J-J, Trovato L, Lewis RE, Segal E, Rath P-M, Hamal P, Rodriguez-Iglesias M, Roilides E, Arikan-Akdagli S, Chakrabarti A, Colombo AL, Fernández MS, Martin-Gomez MT, Badali H, Petrikkos G, Klimko N, Heimann SM, Uzun O, Roudbary M, de la Fuente S, Houbraken J, Risslegger B, Lass-Flörl C, Lackner M. Azole-resistance in Aspergillus terreus and related species: An emerging problem or a rare Phenomenon? Frontiers in Microbiology [Internet]. 2018;9-17.

45. Ullmann AJ, Aguado JM, Arikan-Akdagli S, Denning DW, Groll AH, Lagrou K, Lass-Flörl C, Lewis RE, Munoz P, Verweij PE, Warris A, Ader F, Akova M, Arendrup MC, Barnes RA, Beigelman-Aubry C, Blot S, Bouza E, Brüggemann RJM, Buchheidt D, Cadranel J, Castagnola E, Chakrabarti A, Cuenca-Estrella M, Dimopoulos G, Fortun J, Gangneux J-P, Garbino J, Heinz WJ, Herbrecht R, Heussel CP, Kibbler CC, Klimko N, Kullberg BJ, Lange C, Lehrnbecher T, Löffler J, Lortholary O, Maertens J, Marchetti O, Meis JF, Pagano L, Ribaud P, Richardson M, Roilides E, Ruhnke M, Sanguinetti M, Sheppard DC, Sinkó J, Skiada A, Vehreschild MJGT, Viscoli C, Cornely OA. Diagnosis and management of Aspergillus diseases: executive summary of the 2017 ESCMID-ECMM-ERS guideline. Clinical Microbiology and Infection. 2018;24:e1–38.

46. Tam VH, Pérez C, Ledesma KR, Lewis RE. Transcriptional profiles of pulmonary innate immune responses to isogenic antibiotic-susceptible and multidrug-resistant Pseudomonas aeruginosa. Microbiology and Immunology. 2018;62(4):291–4.

47. Stanzani M, Lewis RE. Development and applications of prognostic risk models in the management of invasive mold disease. Journal of Fungi [Internet]. 2018;4(4).

49. Sassi C, Stanzani M, Lewis RE, Facchini G, Bazzocchi A, Cavo M, Battista G. The utility of contrast-enhanced hypodense sign for the diagnosis of pulmonary invasive mould disease in patients with haematological malignancies. British Journal of Radiology [Internet]. 2018;91(1083).

50. Rizzello I, Castagnetti F, Toschi PG, Bertaccini P, Primavera L, Paolucci M, Faccioli L, Spinardi L, Lewis RE, Cavo M, Stanzani M. Successful treatment of bilateral endogenous Fusarium solani endophthalmitis in a patient with acute lymphocytic leukaemia. Mycoses. 2018;61(1):53–60.

51. Pea F, Lewis RE. Overview of antifungal dosing in invasive candidiasis. Journal of Antimicrobial Chemotherapy. 2018;73:i33–43.

52. Mikulska M, Averbuch D, Tissot F, Cordonnier C, Akova M, Calandra T, Ceppi M, Bruzzi P, Viscoli C, Aljurf M, Averbuch D, Barnes R, Blennow O, Bochud P-Y, Bouza E, Bretagne S, Brüggemann R, Carratala J, Cesaro S, Cornely O, Dalianis T, De La Camara R, Donnelly P, Drgona L, Duarte R, Einsele H, Engelhard D, Fox C, Girmenia C, Groll A, Heldal D, Larsen JH, Herbrecht R, Hirsch H, Johnson E, Klyasova G, Koskuenvo M, Lagrou K, Lewis RE, Ljungman P, Maertens J, Maschmeyer G, Nucci M, Padoin C, Pagano L, Pagliuca A, Racil Z, Ribaud P, Rinaldo C, Puechal VR, Roilides E, Robin C, Rovira M, Rupp M, Sanchez S, Schellongowski P, Sedlacek P, Sinko J, Slavin M, Ferreira IS, Styczynski J, Ward K, Witschi A-T. Fluoroquinolone prophylaxis in haematological cancer patients with neutropenia: ECIL critical appraisal of previous guidelines. Journal of Infection. 2018;76(1):20–37.

53. Lionakis MS, Lewis RE, Kontoyiannis DP. Breakthrough invasive mold infections in the hematology patient: Current concepts and future directions. Clinical Infectious Diseases. 2018;67(10):1621–30.

54. Giannella M, Trecarichi EM, Giacobbe DR, De Rosa FG, Bassetti M, Bartoloni A, Bartoletti M, Losito AR, del Bono V, Corcione S, Tedeschi S, Raffaelli F, Saffioti C, Spanu T, Rossolini GM, Marchese A, Ambretti S, Cauda R, Viscoli C, Lewis RE, Viale P, Tumbarello M. Effect of combination therapy containing a high-dose carbapenem on mortality in patients with carbapenem-resistant Klebsiella pneumoniae bloodstream infection. International Journal of Antimicrobial Agents. 2018;51(2):244–8.

55. Giannella M, Pascale R, Toschi A, Ferraro G, Graziano E, Furii F, Bartoletti M, Tedeschi S, Ambretti S, Lewis RE, Viale P. Treatment duration for Escherichia coli bloodstream infection and outcomes: retrospective single-centre study. Clinical Microbiology and Infection. 2018;24(10):1077–83.

56. Giannella M, Paolucci M, Roncarati G, Vandi G, Pascale R, Trapani F, Bartoletti M, Tedeschi S, Ambretti S, Lewis R, Re MC, Viale P. Potential role of T2Candida in the management of empirical antifungal treatment in patients at high risk of candidaemia: A pilot single-centre study. Journal of Antimicrobial Chemotherapy. 2018;73(10):2856–9.

57. Gaibani P, Campoli C, Lewis RE, Volpe SL, Scaltriti E, Giannella M, Pongolini S, Berlingeri A, Cristini F, Bartoletti M, Tedeschi S, Ambretti S. In vivo evolution of resistant subpopulations of KPC-producing Klebsiella pneumoniae during ceftazidime/avibactam treatment. Journal of Antimicrobial Chemotherapy. 2018;73(6):1525–9.

58. Fernandez IJ, Crocetta FM, Demattè M, Farneti P, Stanzani M, Lewis RE, Fornaciari M, Pasquini E, Sciarretta V. Acute invasive fungal rhinosinusitis in immunocompromised patients: Role of an early diagnosis. Otolaryngology - Head and Neck Surgery (United States). 2018;159(2):386–93.

59. Di Blasi R, Cattaneo C, Lewis RE, Tumbarello M, Angelici L, Dragonetti G, Busca A, Cambò B, Candoni A, Cesarini M, Cesaro S, Delia M, Fanci R, Farina F, Garzia M, Giordano A, Martino B, Melillo L, Nadali G, Perriello V, Picardi M, Quinto AM, Salutari P, Spolzino A, Vacca A, Vetro C, Zancanella M, Nosari A, Aversa F, Pagano L. Febrile events in acute lymphoblastic leukemia: a prospective observational multicentric SEIFEM study (SEIFEM-2012/B ALL). Annals of Hematology. 2018;97(5):791–8.

60. Cesaro S, Dalianis T, Rinaldo CH, Koskenvuo M, Pegoraro A, Einsele H, Cordonnier C, Hirsch HH, Akova M, Aljurf M, Averbuch D, Barnes R, Blennow O, Bochud P-Y, Bouza E, Bretagne S, Brüggemann R, Calandra T, Carratala J, Cornely O, de la Camara R, Donnelly P, Drgona L, Duarte R, Engelhard D, Fox C, Girmenia C, Groll A, Heldal D, Helweg-Larsen J, Herbrecht R, Johnson E, Klyasova G, Lagrou K, Lewis RE, Ljungman P, Maertens J, Mikulska M, Nucci M, Padoin C, Pagano L, Pagliuca A, Racil Z, Ribaud P, Rizzi-Puechal V, Roilides E, Robin C, Rovira M, Rupp M, Sanchez S, Schellongowski P, Sedlacek P, Sinko J, Slavin M, Ferreira IS, Styczynski J, Tissot F, Viscoli C, Ward K, Witschi A-T. ECIL guidelines for the prevention, diagnosis and treatment of BK polyomavirus-associated haemorrhagic cystitis in haematopoietic stem cell transplant recipients. Journal of Antimicrobial Chemotherapy. 2018;73(1):12–21.

61. Bartoletti M, Tedeschi S, Pascale R, Raumer L, Maraolo AE, Palmiero G, Tumietto F, Cristini F, Ambretti S, Giannella M, Lewis RE, Viale P. Differences in the rate of carbapenem-resistant Enterobacteriaceae colonisation or Clostridium difficile infection following frontline treatment with tigecycline vs. meropenem for intra-abdominal infections. International Journal of Antimicrobial Agents. 2018;51(3):516–21.

62. Bartoletti M, Lewis RE, Giannella M, Tedeschi S, Viale P. The role of extended infusion β-lactams in the treatment of bloodstream infections in patients with liver cirrhosis. Expert Review of Anti-Infective Therapy. 2018;16(10):771–9.

63. Bartoletti M, Giannella M, Lewis R, Caraceni P, Tedeschi S, Paul M, Schramm C, Bruns T, Merli M, Cobos-Trigueros N, Seminari E, Retamar P, Muñoz P, Tumbarello M, Burra P, Torrani Cerenzia M, Barsic B, Calbo E, Maraolo AE, Petrosillo N, Galan-Ladero MA, D’Offizi G, Bar Sinai N, Rodríguez-Baño J, Verucchi G, Bernardi M, Viale P, Campoli C, Siccardi G, Ambretti S, Stallmach A, Venditti M, Lucidi C, Ludovisi S, De Cueto M, Navarro MD, Lopez Cortes E, Bouza E, Valerio M, Eworo A, Losito R, Senzolo M, Nadal E, Ottobrelli A, Varguvic M, Badia C, Borgia G, Gentile I, Buonomo AR, Boumis E, Beteta-Lopez A, Rianda A, Taliani G, Grieco S. A prospective multicentre study of the epidemiology and outcomes of bloodstream infection in cirrhotic patients. Clinical Microbiology and Infection. 2018;24(5):546.e1-546.e8.

64. Stanzani M, Vianelli N, Cavo M, Maritati A, Morotti M, Lewis RE. Retrospective cohort analysis of liposomal amphotericin b nephrotoxicity in patients with hematological malignancies. Antimicrobial Agents and Chemotherapy [Internet]. 2017;61(9).

65. Sassi C, Stanzani M, Lewis RE, Vianelli N, Tarsi A, Poerio A, Cavo M, Battista G. Radiologic findings of Fusarium pneumonia in neutropenic patients. Mycoses. 2017;60(2):73–8.

66. Risslegger B, Zoran T, Lackner M, Aigner M, Sánchez-Reus F, Rezusta A, Chowdhary A, Taj-Aldeen SJ, Arendrup MC, Oliveri S, Kontoyiannis DP, Alastruey-Izquierdo A, Lagrou K, Lo Cascio G, Meis JF, Buzina W, Farina C, Drogari-Apiranthitou M, Grancini A, Tortorano AM, Willinger B, Hamprecht A, Johnson E, Klingspor L, Arsic-Arsenijevic V, Cornely OA, Meletiadis J, Prammer W, Tullio V, Vehreschild J-J, Trovato L, Lewis RE, Segal E, Rath P-M, Hamal P, Rodriguez-Iglesias M, Roilides E, Arikan-Akdagli S, Chakrabarti A, Colombo AL, Fernández MS, Martin-Gomez MT, Badali H, Petrikkos G, Klimko N, Heimann SM, Houbraken J, Uzun O, Edlinger M, Fuente SDL, Lass-Flörl C. A prospective international Aspergillus terreus survey: an EFISG, ISHAM and ECMM joint study. Clinical Microbiology and Infection. 2017;23(10):776.e1-776.e5.

67. Polverelli N, Breccia M, Benevolo G, Martino B, Tieghi A, Latagliata R, Sabattini E, Riminucci M, Godio L, Catani L, Nicolosi M, Perricone M, Sollazzo D, Colafigli G, Campana A, Merli F, Vitolo U, Alimena G, Martinelli G, Lewis RE, Vianelli N, Cavo M, Palandri F. Risk factors for infections in myelofibrosis: role of disease status and treatment. A multicenter study of 507 patients. American Journal of Hematology. 2017;92(1):37–41.

68. Pierro A, Ficarelli S, Ayhan N, Morini S, Raumer L, Bartoletti M, Mastroianni A, Prati F, Schivazappa S, Cenni P, Vocale C, Rossini G, Gaibani P, Sambri V, Landini MP, Lewis RE, Charrel RN, Varani S. Characterization of antibody response in neuroinvasive infection caused by Toscana virus. Clinical Microbiology and Infection. 2017;23(11):868–73.

69. Lewis RE, Verweij PE. Animal models for studying triazole resistance in aspergillus fumigatus. Journal of Infectious Diseases. 2017;216:S466–73.

72. Lewis RE. Using carbapenems for carbapenem-resistant Klebsiella pneumoniae-Are we flogging a dead (work)horse antibiotic? Virulence. 2017;8(1):13–4.

73. Heo ST, Tatara AM, Jiménez-Ortigosa C, Jiang Y, Lewis RE, Tarrand J, Tverdek F, Albert ND, Verweij PE, Meis JF, Mikos AG, Perlin DS, Kontoyiannis DP. Changes in in vitro susceptibility patterns of aspergillus to triazoles and correlation with aspergillosis outcome in a tertiary care cancer center, 1999-2015\. Clinical Infectious Diseases. 2017;65(2):216–25.

74. Giannella M, Graziano E, Marconi L, Girometti N, Bartoletti M, Tedeschi S, Tumietto F, Cristini F, Ambretti S, Berlingeri A, Lewis RE, Viale P. Risk factors for recurrent carbapenem resistant Klebsiella pneumoniae bloodstream infection: a prospective cohort study. European Journal of Clinical Microbiology and Infectious Diseases. 2017;36(10):1965–70.

75. Gaibani P, Lewis RE, Volpe SL, Giannella M, Campoli C, Landini MP, Viale P, Re MC, Ambretti S. In vitro interaction of ceftazidime–avibactam in combination with different antimicrobials against KPC-producing Klebsiella pneumoniae clinical isolates. International Journal of Infectious Diseases. 2017;65:1–3.

77. Bartoletti M, Martelli G, Tedeschi S, Morelli M, Bertuzzo V, Tadolini M, Pianta P, Cristini F, Giannella M, Lewis RE, Pinna AD, Viale P. Liver transplantation is associated with good clinical outcome in patients with active tuberculosis and acute liver failure due to anti-tubercular treatment. Transplant Infectious Disease [Internet]. 2017;19(2).

78. Stanzani M, Sassi C, Battista G, Cavo M, Lewis RE. Improved radiographic imaging of invasive fungal disease: The cornerstone to antifungal stewardship in the hematology units? Current Fungal Infection Reports. 2016;10(2):78–86.

79. Potenza L, Vallerini D, Barozzi P, Riva G, Gilioli A, Forghieri F, Candoni A, Cesaro S, Quadrelli C, Maertens J, Rossi G, Morselli M, Codeluppi M, Mussini C, Colaci E, Messerotti A, Paolini A, Maccaferri M, Fantuzzi V, Del Giovane C, Stefani A, Morandi U, Maffei R, Marasca R, Narni F, Fanin R, Comoli P, Romani L, Beauvais A, Viale PL, Latgè JP, Lewis RE, Luppi M. Mucorales-specific T cells in patients with hematologic malignancies. PLoS ONE [Internet]. 2016;11(2).

80. Maschmeyer G, Helweg-Larsen J, Pagano L, Robin C, Cordonnier C, Schellongowski P, Akova M, Aljurf M, Averbuch D, Barnes R, Blennow O, Bochud P-Y, Bouza E, Bretagne S, Brüggemann R, Calandra T, Carratalà J, Cesaro S, Cordonnier C, Cornely O, Dalianis T, De La Camara R, Donnelly P, Drgona L, Duarte R, Einsele H, Engelhard D, Fox C, Girmenia C, Groll A, Heldal D, Helweg-Larsen J, Herbrecht R, Hirsch H, Johnson E, Klyasova G, Koskuenvo M, Lagrou K, Lewis RE, Ljungman P, Maertens J, Maschmeyer G, Mikulska M, Nucci M, Padoin C, Dwe ALLW, Pagliuca A, Racil Z, Ribaud P, Rinaldo C, Rizzi-Puechal V, Roilides E, Robin C, Rovira M, Rupp M, Sanchez S, Schellongowski P, Sedlacek P, Sinko J, Slavin M, Ferreira IS, Styczynski J, Tissot F, Viscoli C, Ward K, Witschi A-T. ECIL guidelines for treatment of Pneumocystis jirovecii pneumonia in non-HIV-infected haematology patients. Journal of Antimicrobial Chemotherapy. 2016;71(9):2405–13.

81. Kyvernitakis A, Torres HA, Jiang Y, Chamilos G, Lewis RE, Kontoyiannis DP. Initial use of combination treatment does not impact survival of 106 patients with haematologic malignancies and mucormycosis: a propensity score analysis. Clinical Microbiology and Infection. 2016;22(9):811.e1-811.e8.

82. Giannella M, Bartoletti M, Morelli M, Cristini F, Tedeschi S, Campoli C, Tumietto F, Bertuzzo V, Ercolani G, Faenza S, Pinna AD, Lewis RE, Viale P. Antifungal prophylaxis in liver transplant recipients: one size does not fit all. Transplant Infectious Disease. 2016;18(4):538–44.

83. Curti A, Ruggeri L, Parisi S, Bontadini A, Dan E, Motta MR, Rizzi S, Trabanelli S, Ocadlikova D, Lecciso M, Giudice V, Fruet F, Urbani E, Papayannidis C, Martinelli G, Bandini G, Bonifazi F, Lewis RE, Cavo M, Velardi A, Lemoli RM. Larger size of donor alloreactive NK cell repertoire correlates with better response to NK cell immunotherapy in elderly acute myeloid leukemia patients. Clinical Cancer Research. 2016;22(8):1914–21.

84. Bellanger A-P, Tatara AM, Shirazi F, Gebremariam T, Albert ND, Lewis RE, Ibrahim AS, Kontoyiannis DP. Statin concentrations below the minimum inhibitory concentration attenuate the virulence of rhizopus oryzae. Journal of Infectious Diseases. 2016;214(1):114–21.

85. Bartoletti M, Giannella M, Lewis RE, Viale P. Bloodstream infections in patients with liver cirrhosis. Virulence. 2016;7(3):309–19.

86. Viale P, Tumietto F, Giannella M, Bartoletti M, Tedeschi S, Ambretti S, Cristini F, Gibertoni C, Venturi S, Cavalli M, De Palma A, Puggioli MC, Mosci D, Callea E, Masina R, Moro ML, Lewis RE. Impact of a hospital-wide multifaceted programme for reducing carbapenem-resistant Enterobacteriaceae infections in a large teaching hospital in northern Italy. Clinical Microbiology and Infection. 2015;21(3):242–7.

87. Viale P, Scudeller L, Pea F, Tedeschi S, Lewis R, Bartoletti M, Sbrojavacca R, Cristini F, Tumietto F, Di Lauria N, Fasulo G, Giannella M. Implementation of a meningitis care bundle in the emergency room reduces mortality associated with acute bacterial meningitis. Annals of Pharmacotherapy. 2015;49(9):978–85.

89. Viale P, Giannella M, Tedeschi S, Lewis R. Treatment of MDR-Gram negative infections in the 21st century: a never ending threat for clinicians. Current Opinion in Pharmacology. 2015;24:30–7.

90. Viale P, Giannella M, Bartoletti M, Tedeschi S, Lewis R. Considerations about antimicrobial stewardship in settings with epidemic extended-spectrum β-Lactamase-Producing or carbapenem-resistant enterobacteriaceae. Infectious Diseases and Therapy. 2015;4:65–83.

91. Stanzani M, Sassi C, Lewis RE, Tolomelli G, Bazzocchi A, Cavo M, Vianelli N, Battista G. High resolution computed tomography angiography improves the radiographic diagnosis of invasive mold disease in patients with hematological malignancies. Clinical Infectious Diseases. 2015;60(11):1603–10.

92. Shirazi F, Lewis RE, Kontoyiannis DP. Micafungin induced apoptosis in candida parapsilosis independent of its susceptibility to micafungin. Microbial Cell. 2015;2(11):445–50.

93. Sassi C, Stanzani M, Lewis RE. Computerized tomographic pulmonary angiography discriminates invasive mould disease of the lung from lymphoma. British Journal of Haematology. 2015;169(4):462–462.

97. Lewis RE, Giannella M, Viale P. Serum galactomannan diagnosis of breakthrough invasive fungal disease. Clinical Infectious Diseases. 2015;60(8):1284.

99. Kontoyiannis DP, Lewis RE. Treatment principles for the management of mold infections. Cold Spring Harbor Perspectives in Medicine [Internet]. 2015;5(4).

100. Giannella M, Ercolani G, Cristini F, Morelli M, Bartoletti M, Bertuzzo V, Tedeschi S, Faenza S, Puggioli C, Lewis RE, Pinna AD, Viale P. High-dose weekly liposomal amphotericin B antifungal prophylaxis in patients undergoing liver transplantation: A prospective phase II trial. Transplantation. 2015;99(4):848–54.

101. Giannella M, Bartoletti M, Morelli MC, Tedeschi S, Cristini F, Tumietto F, Pasqualini E, Danese I, Campoli C, Lauria ND, Faenza S, Ercolani G, Lewis R, Pinna AD, Viale P. Risk factors for infection with carbapenem-resistant Klebsiella pneumoniae after liver transplantation: The importance of pre- and posttransplant colonization. American Journal of Transplantation. 2015;15(6):1708–15.

102. Beyda ND, Liao G, Endres BT, Lewis RE, Garey KW. Innate inflammatory response and immunopharmacologic activity of micafungin, caspofungin, and voriconazole against wild-type and FKS mutant Candida glabrata isolates. Antimicrobial Agents and Chemotherapy. 2015;59(9):5405–12.

103. Bellanger A-P, Albert ND, Lewis RE, Walsh TJ, Kontoyiannis DP. Effect of preexposure to triazoles on susceptibility and virulence of Rhizopus oryzae. Antimicrobial Agents and Chemotherapy. 2015;59(12):7830–2.

104. Tascini C, Sbrana F, Flammini S, Tagliaferri E, Arena F, Leonildi A, Ciullo I, Amadori F, Di Paolo A, Ripoli A, Lewis R, Rossolini GM, Menichetti F, Lambelet P, Forfori F, Viaggi B, Papini F, Urbani L, Malacarne P. Oral gentamicin gut decontamination for prevention of KPC-producing Klebsiella pneumoniae infections: Relevance of concomitant systemic antibiotic therapy. Antimicrobial Agents and Chemotherapy. 2014;58(4):1972–6.

105. Lewis RE, Liao G, Young K, Douglas C, Kontoyiannis DP. Macrophage reporter cell assay for screening immunopharmacological activity of cell wall-active antifungals. Antimicrobial Agents and Chemotherapy. 2014;58(3):1738–43.

106. Lewis RE, Georgiadou SP, Sampsonas F, Chamilos G, Kontoyiannis DP. Risk factors for early mortality in haematological malignancy patients with pulmonary mucormycosis. Mycoses. 2014;57(1):49–55.

107. Lewis RE, Albert ND, Kontoyiannis DP. Comparative pharmacodynamics of posaconazole in neutropenic murine models of invasive pulmonary aspergillosis and mucormycosis. Antimicrobial Agents and Chemotherapy. 2014;58(11):6767–72.

108. Kontoyiannis DP, Lewis RE. Reply to “Risk for invasive fungal infections during acute myeloid leukemia induction therapy: A true association with echinocandins?” Antimicrobial Agents and Chemotherapy. 2014;58(8):4990–1.

110. Gomes MZR, Mulanovich VE, Jiang Y, Lewis RE, Kontoyiannis DP. Incidence density of invasive fungal infections during primary antifungal prophylaxis in newly diagnosed acute myeloid leukemia patients in a tertiary cancer center, 2009 to 2011\. Antimicrobial Agents and Chemotherapy. 2014;58(2):865–73.

111. Gomes MZR, Jiang Y, Mulanovich VE, Lewis RE, Kontoyiannis DP. Effectiveness of primary anti-Aspergillus prophylaxis during remission induction chemotherapy of acute myeloid leukemia. Antimicrobial Agents and Chemotherapy. 2014;58(5):2775–80.

112. Girometti N, Lewis RE, Giannella M, Ambretti S, Bartoletti M, Tedeschi S, Tumietto F, Cristini F, Trapani F, Gaibani P, Viale P. Klebsiella pneumoniae bloodstream infection epidemiology and impact of inappropriate empirical therapy. Medicine (United States). 2014;93(17):298–308.

113. Giannella M, Trecarichi EM, De Rosa FG, Del Bono V, Bassetti M, Lewis RE, Losito AR, Corcione S, Saffioti C, Bartoletti M, Maiuro G, Cardellino CS, Tedeschi S, Cauda R, Viscoli C, Viale P, Tumbarello M. Risk factors for carbapenem-resistant Klebsiella pneumoniae bloodstream infection among rectal carriers: A prospective observational multicentre study. Clinical Microbiology and Infection. 2014;20(12):1357–62.

114. Giannella M, Morelli MC, Cristini F, Ercolani G, Cescon M, Bartoletti M, Tedeschi S, Pasqualini E, Lewis RE, Pinna AD, Viale P. Carbapenem-resistant Klebsiella pneumoniae colonization at liver transplantation: A management challenge. Liver Transplantation. 2014;20(5):631–3.

115. Gaibani P, Lombardo D, Lewis RE, Mercuri M, Bonora S, Landini MP, Ambretti S. In vitro activity and post-antibiotic effects of colistin in combination with other antimicrobials against colistin-resistant KPC-producing Klebsiella pneumoniae bloodstream isolates. Journal of Antimicrobial Chemotherapy. 2014;69(7):1856–65.

116. Dimopoulou D, Hamilos G, Tzardi M, Lewis RE, Samonis G, Kontoyiannis DP. Anidulafungin versus caspofungin in a mouse model of candidiasis caused by anidulafungin-Susceptible candida parapsilosis isolates with different degrees of caspofungin susceptibility. Antimicrobial Agents and Chemotherapy. 2014;58(1):229–36.

117. Di Paolo A, Polillo M, Tascini C, Lewis R, Menichetti F, Danesi R. Different recommendations for daptomycin dosing over time in patients with severe infections. Clinical Infectious Diseases. 2014;58(12):1788–9.

118. Bartoletti M, Giannella M, Caraceni P, Domenicali M, Ambretti S, Tedeschi S, Verucchi G, Badia L, Lewis RE, Bernardi M, Viale P. Epidemiology and outcomes of bloodstream infection in patients with cirrhosis. Journal of Hepatology. 2014;61(1):51–8.

119. Viale P, Giannella M, Lewis R, Trecarichi EM, Petrosillo N, Tumbarello M. Predictors of mortality in multidrug-resistant Klebsiella pneumoniae bloodstream infections. Expert Review of Anti-Infective Therapy. 2013;11(10):1053–63.

120. Tascini C, Tagliaferri E, Giani T, Leonildi A, Flammini S, Casini B, Lewis R, Ferranti S, Rossolini GM, Menichetti F. Synergistic activity of colistin plus rifampin against colistin-resistant kpc-producing klebsiella pneumoniae. Antimicrobial Agents and Chemotherapy. 2013;57(8):3990–3.

121. Stanzani M, Lewis RE, Fiacchini M, Ricci P, Tumietto F, Viale P, Ambretti S, Baccarani M, Cavo M, Vianelli N. A risk prediction score for invasive mold disease in patients with hematological malignancies. PLoS ONE [Internet]. 2013;8(9).

122. Shirazi F, Pontikos MA, Walsh TJ, Albert N, Lewis RE, Kontoyiannis DP. Hyperthermia sensitizes rhizopus oryzae to posaconazole and itraconazole action through apoptosis. Antimicrobial Agents and Chemotherapy. 2013;57(9):4360–8.

123. Petrosillo N, Giannella M, Lewis R, Viale P. Treatment of carbapenem-resistant Klebsiella pneumoniae: The state of the art. Expert Review of Anti-Infective Therapy. 2013;11(2):159–77.

124. Paolucci M, Stanzani M, Melchionda F, Tolomelli G, Castellani G, Landini MP, Varani S, Lewis RE, Sambri V. Routine use of a real-time polymerase chain reaction method for detection of bloodstream infections in neutropaenic patients. Diagnostic Microbiology and Infectious Disease. 2013;75(2):130–4.

125. Lewis RE, Kontoyiannis DP. Epidemiology and treatment of mucormycosis. Future Microbiology. 2013;8(9):1163–75.

126. Lewis RE, Cahyame-Zuniga L, Leventakos K, Chamilos G, Ben-Ami R, Tamboli P, Tarrand J, Bodey GP, Luna M, Kontoyiannis DP. Epidemiology and sites of involvement of invasive fungal infections in patients with haematological malignancies: A 20-year autopsy study. Mycoses. 2013;56(6):638–45.

127. Lewis RE, Ben-Ami R, Best L, Albert N, Walsh TJ, Kontoyiannis DP. Tacrolimus enhances the potency of posaconazole against Rhizopus oryzae in vitro and in an experimental model of mucormycosis. Journal of Infectious Diseases. 2013;207(5):834–41.

128. Lewis RE, Albert NP, Liao G, Wang W, Prince RA, Kontoyiannis DP. High-dose induction liposomal amphotericin B followed by de-escalation is effective in experimental Aspergillus terreus pneumonia. Journal of Antimicrobial Chemotherapy. 2013;68(5):1148–51.

129. Kontoyiannis DP, Georgiadou SP, Wierda WG, Wright S, Albert ND, Ferrajoli A, Keating M, Lewis RE. Impaired bactericidal but not fungicidal activity of polymorphonuclear neutrophils in patients with chronic lymphocytic leukemia. Leukemia and Lymphoma. 2013;54(8):1730–3.

130. Girardis M, Bassetti M, Lewis RE, Viale P. Aggressive versus conservative initiation of antibiotics. The Lancet Infectious Diseases. 2013;13(5):387.

131. Georgiadou SP, Lewis RE, Best L, Torres HA, Champlin RE, Kontoyiannis DP. The impact of prior invasive mold infections in leukemia patients who undergo allo-SCT in the era of triazole-based secondary prophylaxis. Bone Marrow Transplantation. 2013;48(1):141–3.

132. Beyda ND, Regen S, Lewis RE, Garey KW. Immunomodulatory agents as adjunctive therapy for the treatment of resistant Candida species. Current Fungal Infection Reports. 2013;7(2):119–25.

133. Ben-Ami R, Watson CC, Lewis RE, Albert ND, Arias CA, Raad II, Kontoyiannis DP. Drosophila melanogaster as a model to explore the effects of methicillin-resistant Staphylococcus aureus strain type on virulence and response to linezolid treatment. Microbial Pathogenesis. 2013;55(1):16–20.

134. Ben-Ami R, Albert ND, Lewis RE, Kontoyiannis DP. Proangiogenic growth factors potentiate in situ angiogenesis and enhance antifungal drug activity in murine invasive aspergillosis. Journal of Infectious Diseases. 2013;207(7):1066–74.

135. Stanzani M, Battista G, Sassi C, Lewis RE, Tolomelli G, Clissa C, Femia R, Bazzocchi A, Tumietto F, Viale P, Ambretti S, Baccarani M, Vianelli N. Computed tomographic pulmonary angiography for diagnosis of invasive mold diseases in patients with hematological malignancies. Clinical Infectious Diseases. 2012;54(5):610–6.

136. Spellberg B, Ibrahim A, Roilides E, Lewis RE, Lortholary O, Petrikkos G, Kontoyiannis DP, Walsh TJ. Combination therapy for mucormycosis: Why, what, and how? Clinical Infectious Diseases. 2012;54(SUPPL. 1):S73–8.

137. Muhammed M, Feldmesser M, Shubitz LF, Lionakis MS, Sil A, Wang Y, Glavis-Blom J, Lewis RE, Galgiani J, Casadevall A, Kontoyiannis DP, Mylonakis E. Mouse models for the study of fungal pneumonia: A collection of detailed experimental protocols for the study of Coccidioides, Cryptococcus, Fusarium, Histoplasma and combined infection due to Aspergillus-Rhizopus. Virulence. 2012;3(3):15.

138. Lewis RE, Viale P, Kontoyiannis DP. The potential impact of antifungal drug resistance mechanisms on the host immune response to Candida. Virulence. 2012;3(4):368–76.

139. Lewis RE, Viale P. Update on amphotericin B pharmacology and dosing for common systemic mycoses. Current Fungal Infection Reports. 2012;6(4):349–57.

140. Lewis RE, Lortholary O, Spellberg B, Roilides E, Kontoyiannis DP, Walsh TJ. How does antifungal pharmacology differ for mucormycosis versus aspergillosis? Clinical Infectious Diseases. 2012;54(SUPPL. 1):S67–72.

141. Lewis RE. Importance of pharmacokinetic considerations for selecting therapy in the treatment of invasive fungal infections. American Journal of Therapeutics. 2012;19(1):51–63.

142. Kontoyiannis DP, Lewis RE, Lotholary O, Spellberg B, Petrikkos G, Roillides E, Ibrahim A, Walsh TJ. Future directions in mucormycosis research. Clinical Infectious Diseases. 2012;54(SUPPL. 1):S79–85.

143. Julius JM, Gaikwad A, Lowry A, Lewis RE, Lozano RD, Dalrymple JL, Coleman RL, Smith JA. Defining the role of echinocandin catechol functional groups in the development of secondary hepatocellular carcinoma. Journal of Antimicrobial Chemotherapy. 2012;67(2):422–9.

144. Georgiadou SP, Pongas G, Fitzgerald NE, Lewis RE, Rytting M, Marom EM, Kontoyiannis DP. Invasive mold infections in pediatric cancer patients reflect heterogeneity in etiology, presentation, and outcome: A 10-year, single-institution, retrospective study. Journal of the Pediatric Infectious Diseases Society. 2012;1(2):125–35.

145. Chitasombat MN, Kofteridis DP, Jiang Y, Tarrand J, Lewis RE, Kontoyiannis DP. Rare opportunistic (non-Candida, non-Cryptococcus) yeast bloodstream infections in patients with cancer. Journal of Infection. 2012;64(1):68–75.

146. Chavan NL, Young JK, Drezek RA, Lewis R, Bikram M. Interactions of liposome carriers with infectious fungal hyphae reveals the role of β-glucans. Molecular Pharmaceutics. 2012;9(9):2489–96.

147. Cahuayme-Zuniga L, Lewis RE, Mulanovich VE, Kontoyiannis DP. Weekly liposomal amphotericin B as secondary prophylaxis for invasive fungal infections in patients with hematological malignancies. Medical Mycology. 2012;50(5):543–8.

148. Beyda ND, Lewis RE, Garey KW. Echinocandin resistance in Candida species: Mechanisms of reduced susceptibility and therapeutic approaches [Resistencia a equinocandinas en especies de candida: Mecanismos de susceptibilidad reducida y alternativas terapéuticas]. Annals of Pharmacotherapy. 2012;46(7–8):1086–96.

149. Lewis RE, Pongas GN, Albert N, Ben-Ami R, Walsh TJ, Kontoyiannis DP. Activity of deferasirox in Mucorales: Influences of species and exogenous iron. Antimicrobial Agents and Chemotherapy. 2011;55(1):411–3.

150. Lewis RE, Liao G, Wang W, Prince RA, Kontoyiannis DP. Voriconazole pre-exposure selects for breakthrough mucormycosis in a mixed model of Aspergillus fumigatus-Rhizopus oryzae pulmonary infection. Virulence. 2011;2(4):348–55.

151. Lewis RE, Liao G, Hou J, Prince RA, Kontoyiannis DP. Comparative in vivo dose-dependent activity of caspofungin and anidulafungin against echinocandin-susceptible and -resistant Aspergillus fumigatus. Journal of Antimicrobial Chemotherapy. 2011;66(6):1324–31.

152. Lewis RE, Leventakos K, Liao G, Kontoyiannis DP. Efficacy of caspofungin in neutropenic and corticosteroid-immunosuppressed murine models of invasive pulmonary mucormycosis. Antimicrobial Agents and Chemotherapy. 2011;55(7):3584–7.

153. Lewis RE. Pharmacokinetic-pharmacodynamic optimization of triazole antifungal therapy. Current Opinion in Infectious Diseases. 2011;24(SUPPL. 2):S14–29.

154. Lewis RE. Cutaneous mucormycosis in tornado survivors. Current Fungal Infection Reports. 2011;5(4):187–9.

155. Lewis RE. Current concepts in antifungal pharmacology. Mayo Clinic Proceedings. 2011;86(8):805–17.

156. Kontoyiannis DP, Lewis RE. How I treat mucormycosis. Blood. 2011;118(5):1216–24.

157. Gomes MZR, Lewis RE, Kontoyiannis DP. Mucormycosis caused by unusual mucormycetes, non-Rhizopus, -Mucor, and -Lichtheimia species. Clinical Microbiology Reviews. 2011;24(2):411–45.

158. Chen SC-A, Lewis RE, Kontoyiannis DP. Direct effects of non-antifungal agents used in cancer chemotherapy and organ transplantation on the development and virulence of Candida and Aspergillus species. Virulence [Internet]. 2011;2(4).

159. Ben-Ami R, Lewis RE, Kontoyiannis DP. In vitro interactions among echinocandins against Aspergillus fumigatus: Lack of concordance among methods. Medical Mycology. 2011;49(3):285–8.

160. Ben-Ami R, Garcia-Effron G, Lewis RE, Gamarra S, Leventakos K, Perlin DS, Kontoyiannis DP. Fitness and virulence costs of Candida albicans FKS1 hot spot mutations associated with echinocandin resistance. Journal of Infectious Diseases. 2011;204(4):626–35.

161. Milito MA, Kontoyiannis DP, Lewis RE, Liu P, Mawlawi OR, Truong MT, Marom EM. Influence of host immunosuppression on CT findings in invasive pulmonary aspergillosis. Medical Mycology. 2010;48(6):817–23.

162. Lewis RE, Albert ND, Liao G, Hou J, Prince RA, Kontoyiannis DP. Comparative pharmacodynamics of amphotericin B lipid complex and liposomal amphotericin B in a murine model of pulmonary mucormycosis. Antimicrobial Agents and Chemotherapy. 2010;54(3):1298–304.

164. Lewis RE. Antifungal therapeutic drug monitoring. Current Fungal Infection Reports. 2010;4(3):158–67.

165. Leventakos K, Lewis RE, Kontoyiannis DP. Fungal infections in leukemia patients: How do we prevent and treat them? Clinical Infectious Diseases. 2010;50(3):405–15.

166. Kontoyiannis DP, Lewis RE. Studying fungal pathogenesis in Drosophila. Microbe. 2010;5(7):291–6.

167. Evans SE, Scott BL, Clement CG, Larson DT, Kontoyiannis D, Lewis RE, Lasala PR, Pawlik J, Peterson JW, Chopra AK, Klimpel G, Bowden G, Höök M, Xu Y, Tuvim MJ, Dickey BF. Stimulated innate resistance of lung epithelium protects mice broadly against bacteria and fungi. American Journal of Respiratory Cell and Molecular Biology. 2010;42(1):40–50.

168. Evans SE, Leventakos K, Ben-Ami R, You D, Thakkar SG, Lewis RE, Kontoyiannis DP. Toll-deficient Drosophila are resistant to infection by Pneumocystis spp. additional evidence of specificity to mammalian hosts. Virulence. 2010;1(6):523–5.

169. Chamilos G, Bignell EM, Schrettl M, Lewis RE, Leventakos K, May GS, Haas H, Kontoyiannis DP. Exploring the concordance of aspergillus fumigatus pathogenicity in mice and Toll-deficient flies. Medical Mycology. 2010;48(3):506–10.

170. Campo M, Lewis RE, Kontoyiannis DP. Invasive fusariosis in patients with hematologic malignancies at a cancer center: 1998-2009\. Journal of Infection. 2010;60(5):331–7.

171. Ben-Ami R, Varga J, Lewis RE, May GS, Nierman WC, Kontoyiannis DP. Characterization of a 5-azacytidine-induced developmental Aspergillus fumigatus variant. Virulence. 2010;1(3):164–73.

172. Ben-Ami R, Lewis RE, Tarrand J, Leventakos K, Kontoyiannis DP. Antifungal activity of colistin against Mucorales species in vitro and in a murine model of Rhizopus oryzae pulmonary infection. Antimicrobial Agents and Chemotherapy. 2010;54(1):484–90.

173. Ben-Ami R, Lewis RE, Leventakos K, Latgé J-P, Kontoyiannis DP. Cutaneous model of invasive aspergillosis. Antimicrobial Agents and Chemotherapy. 2010;54(5):1848–54.

174. Ben-Ami R, Lewis RE, Kontoyiannis DP. Enemy of the (immunosuppressed) state: An update on the pathogenesis of Aspergillus fumigatus infection. British Journal of Haematology. 2010;150(4):406–17.

175. Ben-Ami R, LaSala PR, Lewis RE, Kontoyiannis DP. Lack of galactomannan reactivity in dematiaceous molds recovered from cancer patients with phaeohyphomycosis. Diagnostic Microbiology and Infectious Disease. 2010;66(2):200–3.

176. Ben-Ami R, Lamaris GA, Lewis RE, Kontoyiannis DP. Interstrain variability in the virulence of Aspergillus fumigatus and Aspergillus terreus in a Toll-deficient Drosophila fly model of invasive aspergillosis. Medical Mycology. 2010;48(2):310–7.

177. Wiederhold NP, Lewis RE. Antifungal activity against Scedosporium species and novel assays to assess antifungal pharmacodynamics against filamentous fungi. Medical Mycology. 2009;47(4):422–32.

178. Tam VH, Ledesma KR, Schilling AN, Lim T-P, Yuan Z, Ghose R, Lewis RE. In vivo dynamics of carbapenem-resistant Pseudomonas aeruginosa selection after suboptimal dosing. Diagnostic Microbiology and Infectious Disease. 2009;64(4):427–33.

179. Sipsas NV, Lewis RE, Tarrand J, Hachem R, Rolston KV, Raad II, Kontoyiannis DP. Candidemia in patients with hematologic malignancies in the era of new antifungal agents (2001-2007): Stable incidence but changing epidemiology of a still frequently lethal infection. Cancer. 2009;115(20):4745–52.

180. Sipsas NV, Lewis RE, Raad II, Kontoyiannis DP. Monotherapy with caspofungin for candidaemia in adult patients with cancer: a retrospective, single institution study. International Journal of Antimicrobial Agents. 2009;34(1):95–8.

181. Roussos P, Lewis RE, Kontoyiannis DP. Azoles and antidepressants: A mini-review of the tolerability of co-administration. Mycoses. 2009;52(5):433–9.

182. Pongas GN, Lewis RE, Samonis G, Kontoyiannis DP. Voriconazole-associated zygomycosis: A significant consequence of evolving antifungal prophylaxis and immunosuppression practices? Clinical Microbiology and Infection. 2009;15(SUPPL. 5):93–7.

183. Pongas GN, Ben-Ami R, Lewis RE, Walsh TJ, Kontoyiannis DP. Culture medium composition affects the lethality of Cunninghamella bertholletiae in a fly model of mucormycosis. Antimicrobial Agents and Chemotherapy. 2009;53(10):4569.

184. Lewis RE, Kontoyiannis DP. Invasive aspergillosis in glucocorticoid-treated patients. Medical Mycology. 2009;47(SUPPL. 1):S271–81.

185. Lewis RE. Overview of the changing epidemiology of candidemia. Current Medical Research and Opinion. 2009;25(7):1732–40.

186. Leventakos K, Ben-Ami R, Lewis RE, Kontoyiannis DP. Immunomodulating effects of antifungal therapy. Current Fungal Infection Reports. 2009;3(4):243–50.

187. Lamaris GA, Ben-Ami R, Lewis RE, Chamilos G, Samonis G, Kontoyiannis DP. Increased virulence of zygomycetes organisms following exposure to voriconazole: a study involving fly and murine models of zygomycosis. Journal of Infectious Diseases. 2009;199(9):1399–406.

188. Kontoyiannis DP, Lewis RE, Marr K. The burden of bacterial and viral infections in hematopoietic stem cell transplant. Biology of Blood and Marrow Transplantation. 2009;15(1 SUPPL.):128–33.

189. Kofteridis DP, Lewis RE, Kontoyiannis DP. Caspofungin-non-susceptible Candida isolates in cancer patients. Journal of Antimicrobial Chemotherapy. 2009;65(2):293–5.

190. Garey KW, Vo QP, Lewis RE, Saengcharoen W, LaRocco MT, Tam VH. Increased bacterial adherence and biomass in Pseudomonas aeruginosa bacteria exposed to clarithromycin. Diagnostic Microbiology and Infectious Disease. 2009;63(1):81–6.

191. Chamilos G, Nobile CJ, Bruno VM, Lewis RE, Mitchell AP, Kontoyiannis DP. Candida albicans Cas5, a regulator of cell wall integrity, is required for virulence in murine and toll mutant fly models. Journal of Infectious Diseases. 2009;200(1):152–7.

192. Ben-Ami R, Luna M, Lewis RE, Walsh TJ, Kontoyiannis DP. A clinicopathological study of pulmonary mucormycosis in cancer patients: Extensive angioinvasion but limited inflammatory response. Journal of Infection. 2009;59(2):134–8.

193. Ben-Ami R, Lewis RE, Raacl II, Kontoyiannis DP. Phaeohyphomycosis in a tertiary care cancer center. Clinical Infectious Diseases. 2009;48(8):1033–41.

194. Ben-Ami R, Lewis RE, Leventakos K, Kontoyiannis DP. Aspergillus fumigatus inhibits angiogenesis through the production of gliotoxin and other secondary metabolites. Blood. 2009;114(26):5393–9.

195. Ben-Ami R, Lewis RE, Kontoyiannis DP. Invasive mould infections in the setting of hematopoietic cell transplantation: Current trends and new challenges. Current Opinion in Infectious Diseases. 2009;22(4):376–84.

196. Lewis RE, Albert ND, Kontoyiannis DP. Efficacy of single-dose liposomal amphotericin B or micafungin prophylaxis in a neutropenic murine model of invasive pulmonary aspergillosis. Antimicrobial Agents and Chemotherapy. 2008;52(11):4178–80.

197. Lewis RE, Albert ND, Kontoyiannis DP. Comparison of the dose-dependent activity and paradoxical effect of caspofungin and micafungin in a neutropenic murine model of invasive pulmonary aspergillosis. Journal of Antimicrobial Chemotherapy. 2008;61(5):1140–4.

198. Lewis RE. What is the “therapeutic range” for voriconazole? Clinical Infectious Diseases. 2008;46(2):212–4.

199. Lamaris GA, Lewis RE, Chamilos G, May GS, Safdar A, Walsh TJ, Raad II, Kontoyiannis DP. Caspofungin-mediated β-glucan unmasking and enhancement of human polymorphonuclear neutrophil activity against Aspergillus and non-Aspergillus hyphae. Journal of Infectious Diseases. 2008;198(2):186–92.

200. Lamaris GA, Esmaeli B, Chamilos G, Desai A, Chemaly RF, Raad II, Safdar A, Lewis RE, Kontoyiannis DP. Fungal endophthalmitis in a tertiary care cancer center: A review of 23 cases. European Journal of Clinical Microbiology and Infectious Diseases. 2008;27(5):343–7.

201. Lamaris GA, Ben-Ami R, Lewis RE, Kontoyiannis DP. Does pre-exposure of Aspergillus fumigatus to voriconazole or posaconazole in vitro affect its virulence and the in vivo activity of subsequent posaconazole or voriconazole, respectively? A study in a fly model of aspergillosis. Journal of Antimicrobial Chemotherapy. 2008;62(3):539–42.

202. Kontoyiannis DP, Lewis RE, Alexander BD, Lortholary O, Dromer F, Gupta KL, John GT, Del Busto R, Klintmalm GB, Somani J, Lyon GM, Pursell K, Stosor V, Muňoz P, Limaye AP, Kalil AC, Pruett TL, Garcia-Diaz J, Humar A, Houston S, House AA, Wray D, Orloff S, Dowdy LA, Fisher RA, Heitman J, Albert ND, Wagener MM, Singh N. Calcineurin inhibitor agents interact synergistically with antifungal agents in vitro against Cryptococcus neoformans isolates: Correlation with outcome in solid organ transplant recipients with cryptococcosis. Antimicrobial Agents and Chemotherapy. 2008;52(2):735–8.

203. Garcia-Effron G, Kontoyiannis DP, Lewis RE, Perlin DS. Caspofungin-resistant Candida tropicalis strains causing breakthrough fungemia in patients at high risk for hematologic malignancies. Antimicrobial Agents and Chemotherapy. 2008;52(11):4181–3.

204. Chamilos G, Lewis RE, Lamaris GA, Albert ND, Kontoyiannis DP. Genomewide screening for genes associated with gliotoxin resistance and sensitivity in Saccharomyces cerevisiae. Antimicrobial Agents and Chemotherapy. 2008;52(4):1325–9.

205. Chamilos G, Lewis RE, Lamaris G, Walsh TJ, Kontoyiannis DP. Zygomycetes hyphae trigger an early, robust proinflammatory response in human polymorphonuclear neutrophils through toll-like receptor 2 induction but display relative resistance to oxidative damage. Antimicrobial Agents and Chemotherapy. 2008;52(2):722–4.

206. Chamilos G, Lewis RE, Kontoyiannis DP. Delaying amphotericin B-based frontline therapy significantly increases mortality among patients with hematologic malignancy who have zygomycosis. Clinical Infectious Diseases. 2008;47(4):503–9.

207. Chamilos G, Lewis RE, Hu J, Xiao L, Zal T, Gilliet M, Halder G, Kontoyiannis DP. Drosophila melanogaster as a model host to dissect the immunopathogenesis of zygomycosis. Proceedings of the National Academy of Sciences of the United States of America. 2008;105(27):9367–72.

208. Ben-Ami R, Lewis RE, Kontoyiannis DP. Immunopharmacology of modern antifungals. Clinical Infectious Diseases. 2008;47(2):226–35.

209. Atkinson BJ, Lewis RE, Kontoyiannis DP. Candida lusitaniae fungemia in cancer patients: Risk factors for amphotericin B failure and outcome. Medical Mycology. 2008;46(6):541–6.

210. Orciuolo E, Stanzani M, Canestraro M, Galimberti S, Carulli G, Lewis R, Petrini M, Komanduri KV. Effects of Aspergillus fumigatus gliotoxin and methylprednisolone on human neutrophils: Implications for the pathogenesis of invasive aspergillosis. Journal of Leukocyte Biology. 2007;82(4):839–48.

211. Mulanovich V, Lewis RE, Raad II, Kontoyiannis DP. Random plasma concentrations of voriconazole decline over time. Journal of Infection. 2007;55(5):e129–30.

212. Lewis RE, Liao G, Hou J, Chamilos G, Prince RA, Kontoyiannis DP. Comparative analysis of amphotericin B lipid complex and liposomal amphotericin B kinetics of lung accumulation and fungal clearance in a murine model of acute invasive pulmonary aspergillosis. Antimicrobial Agents and Chemotherapy. 2007;51(4):1253–8.

213. Lewis RE, Chamilos G, Prince RA, Kontoyiannis DP. Pretreatment with empty liposomes attenuates the immunopathology of invasive pulmonary aspergillosis in corticosteroid-immunosuppressed mice. Antimicrobial Agents and Chemotherapy. 2007;51(3):1078–81.

214. Lewis RE. Pharmacodynamic implications for use of antifungal agents. Current Opinion in Pharmacology. 2007;7(5):491–7.

215. Lamaris GA, Chamilos G, Lewis RE, Kontoyiannis DP. Virulence studies of Scedosporium and Fusarium species in Drosophila melanogaster. Journal of Infectious Diseases. 2007;196(12):1860–4.

216. Kontoyiannis DP, Chamilos G, Lewis RE, Giralt S, Cortes J, Raad II, Manning JT, Han X. Increased bone marrow iron stores is an independent risk factor for invasive aspergillosis in patients with high-risk hematologic malignancies and recipients of allogeneic hematopoietic stem cell transplantation. Cancer. 2007;110(6):1303–6.

217. Kontoyiannis DP, Chamilos G, Hassan SA, Lewis RE, Albert ND, Tarrand JJ. Increased culture recovery of zygomycetes under physiologic temperature conditions. American Journal of Clinical Pathology. 2007;127(2):208–12.

218. Chou LS, Lewis RE, Ippoliti C, Champlin RE, Kontoyiannis DP. Caspofungin as primary antifungal prophylaxis in stem cell transplant recipients. Pharmacotherapy. 2007;27(12 I):1644–50.

219. Chamilos G, Luna M, Lewis RE, Chemaly R, Raad II, Kontoyiannis DP. Effects of liposomal amphotericin B versus an amphotericin B lipid complex on liver histopathology in patients with hematologic malignancies and invasive fungal infections: A retrospective, nonrandomized autopsy study. Clinical Therapeutics. 2007;29(9):1980–6.

220. Chamilos G, Lionakis MS, Lewis RE, Kontoyiannis DP. Role of mini-host models in the study of medically important fungi. Lancet Infectious Diseases. 2007;7(1):42–55.

221. Chamilos G, Lewis RE, Kontoyiannis DP. Multidrug-resistant endosymbiotic bacteria account for the emergence of zygomycosis: A hypothesis. Fungal Genetics and Biology. 2007;44(2):88–92.

222. Chamilos G, Lewis RE, Albert N, Kontoyiannis DP. Paradoxical effect of echinocandins across Candida species in vitro: Evidence for Echinocandin-Specific and Candida species-related differences. Antimicrobial Agents and Chemotherapy. 2007;51(6):2257–9.

223. Wiederhold NP, Tam VH, Chi J, Prince RA, Kontoyiannis DP, Lewis RE. Pharmacodynamic activity of amphotericin B deoxycholate is associated with peak plasma concentrations in a neutropenic murine model of invasive pulmonary aspergillosis. Antimicrobial Agents and Chemotherapy. 2006;50(2):469–73.

224. Singh N, Limaye AP, Forrest G, Safdar N, Muñoz P, Pursell K, Houston S, Rosso F, Montoya JG, Patton P, Del Busto R, Aguado JM, Fisher RA, Klintmalm GB, Miller R, Wagener MM, Lewis RE, Kontoyiannis DP, Husain S. Combination of voriconazole and caspofungin as primary therapy for invasive aspergillosis in solid organ transplant recipients: A prospective, multicenter, observational study. Transplantation. 2006;81(3):320–6.

225. Lionakis MS, Chamilos G, Lewis RE, Wiederhold NP, Raad II, Samonis G, Kontoyiannis DP. Pentamidine is active in a neutropenic murine model of acute invasive pulmonary fusariosis. Antimicrobial Agents and Chemotherapy. 2006;50(1):294–7.

226. Lewis RE, Wiederhold NP, Prince RA, Kontoyiannis DP. In vitro pharmacodynamics of rapid versus continuous infusion of amphotericin B deoxycholate against Candida species in the presence of human serum albumin. Journal of Antimicrobial Chemotherapy. 2006;57(2):288–93.

227. Lewis RE. Managing drug interactions in the patient with aspergillosis. Medical Mycology. 2006;44(SUPPL. 1):349–56.

228. Lewis RE. Decision making in antifungal monotherapy versus combination therapy. Pharmacotherapy. 2006;26(6 II):61S-67S.

229. Lewis R. Judgments of value, judgments of fact: The ethical dimension of biohistorical research. Public Historian. 2006;28(1):93–9\.

230. Lamaris GA, Chamilos G, Lewis RE, Safdar A, Raad II, Kontoyiannis DP. Scedosporium infection in a tertiary care cancer center: A review of 25 cases from 1989-2006. Clinical Infectious Diseases. 2006;43(12):1580–4.

231. Kontoyiannis DP, Lewis RE. Invasive zygomycosis: Update on pathogenesis, clinical manifestations, and management. Infectious Disease Clinics of North America. 2006;20(3):581–607.

232. Garey KW, Neuhauser MM, Bearden DT, Cannon JP, Lewis RE, Gentry LO, Kontoyiannis DP. Evaluation of antifungals in the surgical intensive care unit: A multi-institutional study. Mycoses. 2006;49(3):226–31.

233. Dennis CG, Greco WR, Brun Y, Youn R, Slocum HK, Bernacki RJ, Lewis R, Wiederhold N, Holland SM, Petraitiene R, Walsh TJ, Segal BH. Effect of amphotericin B and micafungin combination on survival, histopathology, and fungal burden in experimental aspergillosis in the p47 phox-/- mouse model of chronic granulomatous disease. Antimicrobial Agents and Chemotherapy. 2006;50(2):422–7.

234. Chamilos G, Luna M, Lewis RE, Bodey GP, Chemaly R, Tarrand JJ, Safdar A, Raad II, Kontoyiannis DP. Invasive fungal infections in patients with hematologic malignancies in a tertiary care cancer center: An autopsy study over a 15-year period (1989-2003). Haematologica. 2006;91(7):986–9.

235. Chamilos G, Lionakis MS, Lewis RE. Erratum: Drosophila melanogaster as a facile model for large-scale studies of virulence mechanisms and antifungal drug efficacy in Candida species (Journal of Infectious Diseases (2006) 193 (1014-1022)). Journal of Infectious Diseases. 2006;194(9):1342.

236. Chamilos G, Lionakis MS, Lewis RE, Lopez-Ribot JL, Saville SP, Albert ND, Halder G, Kontoyiannis DP. Drosophila melanogaster as a facile model for large-scale studies of virulence mechanisms and antifungal drug efficacy in Candida species. Journal of Infectious Diseases. 2006;193(7):1014–22.

237. Chamilos G, Lewis RE, Kontoyiannis DP. Lovastatin has significant activity against zygomycetes and interacts synergistically with voriconazole. Antimicrobial Agents and Chemotherapy. 2006;50(1):96–103.

238. Chamilos G, Lewis RE, Kontoyiannis DP. Inhibition of Candida parapsilosis mitochondrial respiratory pathways enhances susceptibility to caspofungin. Antimicrobial Agents and Chemotherapy. 2006;50(2):744–7.

239. Ashley ESD, Lewis R, Lewis JS, Martin C, Andes D. Pharmacology of systemic antifungal agents. Clinical Infectious Diseases. 2006;43(SUPPL. 1):S28–39.

240. Wiederhold NP, Kontoyiannis DP, Prince RA, Lewis RE. Attenuation of the activity of caspofungin at high concentrations against Candida albicans: Possible role of cell wall integrity and calcineurin pathways. Antimicrobial Agents and Chemotherapy. 2005;49(12):5146–8.

241. Wiederhold NP, Coyle EA, Raad II, Prince RA, Lewis RE. Antibacterial activity of linezolid and vancomycin in an vitro pharmacodynamic model of Gram-positive catheter-related bacteraemia. Journal of Antimicrobial Chemotherapy. 2005;55(5):792–5.

242. Tam VH, Schilling AN, Vo G, Kabbara S, Kwa AL, Wiederhold NP, Lewis RE. Pharmacodynamics of polymyxin B against Pseudomonas aeruginosa. Antimicrobial Agents and Chemotherapy. 2005;49(9):3624–30.

243. Stanzani M, Orciuolo E, Lewis R, Kontoyiannis DP, Martins SLR, St. John LS, Komanduri KV. Aspergillus fumigatus suppresses the human cellular immune response via gliotoxin-mediated apoptosis of monocytes. Blood. 2005;105(6):2258–65.

244. Raad II, Hanna HA, Boktour M, Chaiban G, Hachem RY, Dvorak T, Lewis R, Murray BE. Vancomycin-resistant Enterococcus faecium: Catheter colonization, esp gene, and decreased susceptibility to antibiotics in biofilm. Antimicrobial Agents and Chemotherapy. 2005;49(12):5046–50.

245. Lionakis MS, Lewis RE, Torres HA, Albert ND, Raad II, Kontoyiannis DP. Increased frequency of non-fumigatus Aspergillus species in amphotericin B- or triazole-pre-exposed cancer patients with positive cultures for aspergilli. Diagnostic Microbiology and Infectious Disease. 2005;52(1):15–20.

246. Lionakis MS, Lewis RE, May GS, Wiederhold NP, Albert ND, Halder G, Kontoyiannis DP. Toll-deficient Drosophila flies as a fast, high-throughput model for the study of antifungal drug efficacy against invasive aspergillosis and Aspergillus virulence. Journal of Infectious Diseases. 2005;191(7):1188–95.

247. Lionakis MS, Lewis RE, Chamilos G, Kontoyiannis DP. Aspergillus susceptibility testing in patients with cancer and invasive aspergillosis: Difficulties in establishing correlation between in vitro susceptibility data and the outcome of initial amphotericin B therapy. Pharmacotherapy. 2005;25(9):1174–80.

248. Lionakis MS, Lahdenranta J, Sun J, Liu W, Lewis RE, Albert ND, Pasqualini R, Arap W, Kontoyiannis DP. Development of a ligand-directed approach to study the pathogenesis of invasive aspergillosis. Infection and Immunity. 2005;73(11):7747–58.

249. Lewis RE, Wiederhold NP, Lionakis MS, Prince RA, Kontoyiannis DP. Frequency and species distribution of gliotoxin-producing Aspergillus isolates recovered from patients at a tertiary-care cancer center. Journal of Clinical Microbiology. 2005;43(12):6120–2.

250. Lewis RE, Wiederhold NP, Klepser ME. In vitro pharmacodynamics of amphotericin B, itraconazole, and voriconazole against Aspergillus, Fusarium, and Scedosporium spp. Antimicrobial Agents and Chemotherapy. 2005;49(3):945–51.

251. Lewis RE, Wiederhold NP, Chi J, Han XY, Komanduri KV, Kontoyiannis DP, Prince RA. Detection of gliotoxin in experimental and human aspergillosis. Infection and Immunity. 2005;73(1):635–7.

252. Lewis RE, Wiederhold NP. Murine model of invasive aspergillosis. Methods in molecular medicine. 2005;118:129–42.

253. Lewis RE, Kontoyiannis DP. Micafungin in combination with voriconazole in Aspergillus species: A pharmacodynamic approach for detection of combined antifungal activity in vitro. Journal of Antimicrobial Chemotherapy. 2005;56(5):887–92.

254. Kontoyiannis DP, Lionakis MS, Lewis RE, Chamilos G, Healy M, Perego C, Safdar A, Kantarjian H, Champlin R, Walsh TJ, Raad II. Zygomycosis in a tertiary-care cancer center in the era of Aspergillus-active antifungal therapy: A case-control observational study of 27 recent cases. Journal of Infectious Diseases. 2005;191(8):1350–60.

255. Chamilos G, Marom EM, Lewis RE, Lionakis MS, Kontoyiannis DP. Predictors of pulmonary zygomycosis versus invasive pulmonary aspergillosis in patients with cancer. Clinical Infectious Diseases. 2005;41(1):60–6.

256. Wiederhold NP, Kontoyiannis DP, Chi J, Prince RA, Tam VH, Lewis RE. Pharmacodynamics of caspofungin in a murine model of invasive pulmonary aspergillosis: Evidence of concentration-dependent activity. Journal of Infectious Diseases. 2004;190(8):1464–71.

257. Tam VH, Schilling AN, Lewis RE, Melnick DA, Boucher AN. Novel approach to characterization of combined pharmacodynamic effects of antimicrobial agents. Antimicrobial Agents and Chemotherapy. 2004;48(11):4315–21.

258. Liu W, May GS, Lionakis MS, Lewis RE, Kontoyiannis DP. Extra copies of the Aspergillus fumigatus squalene epoxidase gene confer resistance to terbinafine: Genetic approach to studying gene dose-dependent resistance to antifungals in A. fumigatus. Antimicrobial Agents and Chemotherapy. 2004;48(7):2490–6.

259. Lewis RE, Kontoyiannis DP. Erratum: Challenges in designing animal studies to detect antagonism of polyene activity (Antimicrobial Agents and Chemotherapy (2004) 48:8 (3211-3212)). Antimicrobial Agents and Chemotherapy. 2004;48(10):4072.

260. Lewis RE, Kantoyiannis DP, Najvar LK, Graybill JR, Cacciapuoti AF. Challenges in designing animal studies to detect antagonism of polyene activity.Antimicrobial Agents and Chemotherapy. 2004;48(8):3211–2.

261. Kontoyiannis DP, Lewis RE. Toward more effective antifungal therapy: The prospects of combination therapy. British Journal of Haematology. 2004;126(2):165–75.

262. Kontoyiannis DP, Lewis RE. Editorial comment: Is fluconazole the only factor? Infections in Medicine. 2004;21(1):40.

263. Hoffman BR, DelasAlas H, Blanco K, Wiederhold N, Lewis RE, Williams L. Screening of antibacterial and antifungal activities of ten medicinal plants from Ghana. Pharmaceutical Biology. 2004;42(1):13–7.

264. Barker KS, Crisp S, Wiederhold N, Lewis RE, Bareither B, Eckstein J, Barbuch R, Bard M, Rogers PD. Genome-wide expression profiling reveals genes associated with amphotericin B and fluconazole resistance in experimentally induced antifungal resistant isolates of Candida albicans. Journal of Antimicrobial Chemotherapy. 2004;54(2):376–85.

265. Andrews LB, Buenger N, Bridge J, Rosenow L, Stoney D, Gaensslen RE, Karamanski T, Lewis R, Paradise J, Inlander A, Gonen D. Constructing ethical guidelines for biohistory. Science. 2004;304(5668):215–6.

266. Wiederhold NP, Lewis RE, Kontoyiannis DP. Invasive aspergillosis in patients with hematologic malignancies. Pharmacotherapy. 2003;23(12 I):1592–610.

267. Wiederhold NP, Lewis RE. The echinocandin antifungals: An overview of the pharmacology, spectrum and clinical efficacy. Expert Opinion on Investigational Drugs. 2003;12(8):1313–33.

268. Torres HA, Rivero GA, Lewis RE, Hachem R, Raad II, Kontoyiannis DP. Aspergillosis caused by non-fumigatus Aspergillus species: Risk factors and in vitro susceptibility compared with Aspergillus fumigatus. Diagnostic Microbiology and Infectious Disease. 2003;46(1):25–8.

269. Rogers PD, Kramer RE, Crews JK, Lewis RE. The activity of amphotericin B against Candida albicans is not directly associated with extracellular calcium concentration. Journal of Antimicrobial Chemotherapy. 2003;51(2):305–12.

270. Liu W, Lionakis MS, Lewis RE, Wiederhold N, May GS, Kontoyiannis DP. Attenuation of itraconazole fungicidal activity following preexposure of aspergillus fumigatus to fluconazole. Antimicrobial Agents and Chemotherapy. 2003;47(11):3592–7.

271. Lionakis MS, Lewis RE, Samonis G, Kontoyiannis DP. Pentamidine is active in vitro against Fusarium species. Antimicrobial Agents and Chemotherapy. 2003;47(10):3252–9.

272. Lewis RE, Wiederhold NP. The solubility ceiling: A rationale for continuous infusion amphotericin B therapy? [9]. Clinical Infectious Diseases. 2003;37(6):871–2.

273. Kontoyiannis DP, Lewis RE, Osherov N, Albert ND, May GS. Combination of caspofungin with inhibitors of the calcineurin pathway attenuates growth in vitro in Aspergillus species. Journal of Antimicrobial Chemotherapy. 2003;51(2):313–6.

274. Kontoyiannis DP, Lewis RE, Lionakis MS, Albert ND, May GS, Raad II. Sequential exposure of Aspergillus fumigatus to itraconazole and caspofungin: Evidence of enhanced in vitro activity. Diagnostic Microbiology and Infectious Disease. 2003;47(2):415–9.

275. Kontoyiannis DP, Lewis RE. Combination chemotherapy for invasive fungal infections: What laboratory and clinical studies tell us so far. Drug Resistance Updates. 2003;6(5):257–69.

276. Kontoyiannis DP, Hachem R, Lewis RE, Rivero GA, Torres HA, Thornby J, Champlin R, Kantarjian H, Bodey GP, Raad II. Efficacy and toxicity of caspofungin in combination with liposomal amphotericin B as primary or salvage treatment of invasive aspergillosis in patients with hematologic malignancies. Cancer. 2003;98(2):292–9.

277. Antoniadou A, Torres HA, Lewis RE, Thornby J, Bodey GP, Tarrand JJ, Han X-Y, Rolston KVI, Safdar A, Raad II, Kontoyiannis DP. Candidemia in a Tertiary Care Cancer Center: In vitro susceptibility and its association with outcome of initial antifungal therapy. Medicine. 2003;82(5):309–21.

278. Roling EE, Klepser ME, Wasson A, Lewis RE, Ernst EJ, Pfaller MA. Antifungal activities of fluconazole, caspofungin (MK0991), and anidulafungin (LY 303366) alone and in combination against Candida spp. and Crytococcus neoformans via time-kill methods. Diagnostic Microbiology and Infectious Disease. 2002;43(1):13–7.

279. Lewis RE, Prince RA, Chi J, Kontoyiannis DP. Itraconazole preexposure attenuates the efficacy of subsequent amphotericin B therapy in a murine model of acute invasive pulmonary aspergillosis. Antimicrobial Agents and Chemotherapy. 2002;46(10):3208–14.

280. Lewis RE, Lo H-J, Raad II, Kontoyiannis DP. Lack of catheter infection by the efg1/efg1 cph1/cph1 double-null mutant, a Candida albicans strain that is defective in filamentous growth. Antimicrobial Agents and Chemotherapy. 2002;46(4):1153–5.

281. Lewis RE, Kontoyiannis DP, Darouiche RO, Raad II, Prince RA. Antifungal activity of amphotericin B, fluconazole, and voriconazole in an in vitro model of Candida catheter-related bloodstream infection. Antimicrobial Agents and Chemotherapy. 2002;46(11):3499–505.

282. Lewis RE, Diekema DJ, Messer SA, Pfaller MA, Klepser ME. Comparison of Etest, chequerboard dilution and time-kill studies for the detection of synergy or antagonism between antifungal agents tested against Candida species. Journal of Antimicrobial Chemotherapy. 2002;49(2):345–51.

283. Lewis RE. Pharmacotherapy of Candida bloodstream infections: New treatment options, new era. Expert Opinion on Pharmacotherapy. 2002;3(8):1039–57.

284. Kontoyiannis DP, Reddy BT, Torres HA, Luna M, Lewis RE, Tarrand J, Bodey GP, Raad II. Pulmonary candidiasis in patients with cancer: An autopsy study. Clinical Infectious Diseases. 2002;34(3):400–3.

285. Kontoyiannis DP, Lewis RE, May GS, Osherov N, Rinaldi MG. Aspergillus nidulans is frequently resistant to amphotericin B. Mycoses. 2002;45(9–10):406–7.

286. Kontoyiannis DP, Lewis RE. Antifungal drug resistance of pathogenic fungi. Lancet. 2002;359(9312):1135–44.

287. Pietrucha-Dilanchian P, Lewis RE, Ahmad H, Lechin AE. Candida lusitaniae catheter-related sepsis. Annals of Pharmacotherapy. 2001;35(12):1570–4.

288. Lewis RE, Kontoyiannis DP. Rationale for combination antifungal therapy. Pharmacotherapy. 2001;21(8 SUPPL. 2):149S-164S.

289. Kontoyiannis DP, Andersson BS, Lewis RE, Raad II. Progressive disseminated aspergillosis in a bone marrow transplant recipient: response with a high-dose lipid formulation of amphotericin B. Clinical infectious diseases : an official publication of the Infectious Diseases Society of America. 2001;32(5):E94-96.

290. Klepser ME, Lewis RE, Ernst EJ, Rosemarie Petzold C, Bailey EM, Burgess DS, Carver PL, Lacy MK, Mercier R-C, Nicolau DP, Zhanel GG, Pfaller MA. Multi-center evaluation of antifungal time-kill methods. Journal of Infectious Disease Pharmacotherapy. 2001;5(2):29–41.

291. Keele DJ, DeLallo VC, Lewis RE, Ernst EJ, Klepser ME. Evaluation of amphotericin B and flucytosine in combination against Candida albicans and Cryptococcus neoformans using time-kill methodology. Diagnostic Microbiology and Infectious Disease. 2001;41(3):121–6.

292. Lewis RE, Klepser ME, Pfaller MA. In vitro pharmacodynamic characteristics of flucytosine determined by time-kill methods. Diagnostic Microbiology and Infectious Disease. 2000;36(2):101–5.

293. Lewis RE, Klepser ME, Ernst EJ, Snabes MA, Jones RN. Comparison of oral immediate-release (IR) and extended-release (ER) metronidazole bactericidal activity against Bacteroides spp. using an in vitro model of infection. Diagnostic Microbiology and Infectious Disease. 2000;37(1):51–5.

294. Kontoyiannis DP, Lewis RE, Sagar N, May G, Prince RA, Rolston KVI. Itraconazole-amphotericin B antagonism in Aspergillus fumigatus: An E-test-based strategy. Antimicrobial Agents and Chemotherapy. 2000;44(10):2915–8.

295. Klepser ME, Malone D, Lewis RE, Ernst EJ, Pfaller MA. Evaluation of voriconazole pharmacodynamics using time-kill methodology. Antimicrobial Agents and Chemotherapy. 2000;44(7):1917–20.

296. Lewis RE, Klepser ME, Pfaller MA. Combination systemic antifungal therapy for cryptococcosis, candidiasis, and aspergillosis. Journal of Infectious Disease Pharmacotherapy. 1999;3(4):61–83.

297. Lewis RE, Klepser ME, Ernst EJ, Lund BC, Biedenbach DJ, Jones RN. Evaluation of low-dose, extended-interval clindamycin regimens against Staphylococcus aureus and Streptococcus pneumoniae using a dynamic in vitro model of infection. Antimicrobial Agents and Chemotherapy. 1999;43(8):2005–9.

298. Lewis RE, Klepser ME. The changing face of nosocomial candidemia: Epidemiology, resistance, and drug therapy. American Journal of Health-System Pharmacy. 1999;56(6):525–36.

299. Lewis RE, Lund BC, Klepser ME, Ernst EJ, Pfaller MA. Assessment of antifungal activities of fluconazole and amphotericin b administered alone and in combination against Candida albicans by using a dynamic in vitro mycotic infection model. Antimicrobial Agents and Chemotherapy. 1998;42(6):1382–6.

300. Lewis RE, Klepser ME, Pfaller MA. Update on clinical antifungal susceptibility testing for Candida species. Pharmacotherapy. 1998;18(3):509–15.

301. Lewis RE, Klepser ME. Update on clindamycin: New pharmacokinetic and pharmacodynamic data. Infections in Medicine. 1998;15(10):726–31.

302. Klepser ME, Lewis RE, Pfaller MA. Therapy of Candida infections: Susceptibility testing, resistance, and therapeutic options. Annals of Pharmacotherapy. 1998;32(12):1353–61.

303. Klepser ME, Ernst EJ, Lewis RE, Ernst ME, Pfaller MA. Influence of test conditions on antifungal time-kill curve results: Proposal for standardized methods. Antimicrobial Agents and Chemotherapy. 1998;42(5):1207–12.

## Bookchapters

1. Shelbourn S, Lewis RE, Kontoyiannis DP. Clinical management of infections in neutropenic patients. Hematology: Basic Principles and Practice. 8<sup>th</sup> edition. Hoffman, Benz and Shattil ed. 2021.

2. Kontoyiannis DP and Lewis RE. Agents of Mucormycosis and Entomophthoramycosis. In: Principles and Practice of Infectious Diseases. Mandell, Bennet and Dolin eds. 10<sup>th</sup> edition. 2021.

3. Shelbourn S, Lewis RE, Kontoyiannis DP. Clinical management of infections in neutropenic patients. Hematology: Basic Principles and Practice. 7<sup>th</sup> edition. Hoffman, Benz and Shattil ed. 2017.
 
4. Kontoyiannis DP and Lewis RE. Agents of Mucormycosis and Entomophthoramycosis. In: Principles and Practice of Infectious Diseases. Mandell, Bennet and Dolin eds. 9<sup>th</sup> edition. 2019.

5. Lewis RE. Pharmacokinetics of azole antifungals, Chapter 7. In: Winter’s Basic Clinical Pharmacokinetics 6<sup>th</sup> edition. Wolters Kluwer, 2018.

6. Lewis RE and Kontoyiannis DP. Butenafine. In: Use of antibiotics. Kucer 7 th Ed. American Society for Microbiology Press, 2017.

7. Lewis RE, Beyda N, Kontoyiannis DP. Caspofungin In: Use of antibiotics. Kucer 7<sup>th</sup> Ed. American Society for Microbiology Press, 2017.

8.  Shelbourn S, Lewis RE, Kontoyiannis DP. Clinical management of infections in neutropenic patients. Hematology: Basic Principles and Practice. 6<sup>th</sup> edition. Hoffman, Benz and Shattil ed. 2017.

9. Cleary JD, Lewis RE. Fungal infections. Koda-Kimble & Young's Applied Therapeutics, 11th Edition 2015.
 
10. Lewis RE., Rogers PD. Invasive Fungal Infections. Pharmacotherapy Essentials Casebook 4th Ed. MacGraw- Hill. Revised Chapter 2017.

11. Lewis RE. Update on Invasive fungal infections. Pharmacotherapy Self-Assessment Program-15 (PSAP-15). American College of Clinical Pharmacy.

12.  Viale P, Lewis RE. Voriconazole treatment in invasive candidiasis. Voriconazole: Pharmacokinetics, Role in Therapeutic Drug Monitoring and Clinical Outcomes 2015. p. 41-52.

13. Kontoyiannis DP & Lewis RE. Agents of Mucormycosis and Entomophthoramycosis. In: Principles and Practice of Infectious Diseases. Mandell, Bennet and Dolin eds. 8<sup>th</sup> edition. 2014.

14. Lewis RE. Invasive Fungal Infections. Pharmacotherapy Essentials Casebook 3<sup>rd</sup> Ed. McGraw-Hill. Revised Chapter. 2013

15. Lewis RE. Management of Mucormycosis. Clinical Decision Support in Medicine 2014.

16. Lewis RE. Invasive Fungal Infections. Pharmacotherapy Essentials 3<sup>rd</sup> Ed. McGraw-Hill. Revised Chapter 2011.

17. Shelbourn S, Lewis RE, Kontoyiannis DP. Management of fever in neutropenic patients. Hematology: Basic Principles and Practice. 5<sup>th</sup> edition. Hoffman, Benz and Shattil ed. 2014.

18. Lewis RE & Kontoyiannis DP. The clinical significance of antifungal resistance in _Candida_ species. Candida and Candidiasis. American Society for Microbiology Press 2011.

19. Lewis RE and Kontoyiannis DP. Butenafine. In: Use of antibiotics. Kucer 6<sup>th</sup> Ed. American Society for Microbiology Press, 2010.

21. Lewis RE and Kontoyiannis DP. Glucan synthesis inhibitors. In: Use of antibiotics. Kucer 6<sup>th</sup> Ed. American Society for Microbiology Press, 2010.

22. Lewis RE and DS Perlin. Antifungal drug resistance. In: Management of Infections in Cancer Patients. Humana Press, 2011.

23. Lewis RE, Rogers PD. Invasive Fungal Infections. Pharmacotherapy Essentials 2<sup>nd</sup> Ed. MacGraw-Hill. Revised Chapter, 2010. 

24. Kontoyiannis DP & Lewis RE. Agents of Mucormycosis and Entomophthoramycosis. In: Principles and Practice of Infectious Diseases. Mandall, Bennet and Dolin eds. 7<sup>th</sup> edition

25. Lewis RE. Polyene antifungal agents. In: Aspergillosis: from Diagnosis to Prevention. In Pasqualotto AC ed. Springer Press. 2009.

26. Lewis RE. Antifungal Drug Interactions _In:_ Aspergillus and Aspergillosis. ASM Press 2008.

27. Lewis RE, Fothergill A. Antifungal Pharmacology. In: Hospenthal and Rinaldi. Clinical Mycology. Humana Press. 2008.

28. Lewis RE, Rogers PD. Invasive Fungal Infections. Pharmacotherapy Essentials. MacGraw-Hill. 2007.

29. Lewis RE. Infections in Immunocompromised Patients. In: Helms R, Quan DJ, eds. Textbook of Therapeutics: Drug and Disease Management Eighth Edition. Lippincott, Williams and Wilkins.2007

30. Wiederhold NP, Lewis RE. Murine model of invasive aspergillosis. Methods in Molecular Mycology. Academic Press. 2005.

31. Lewis RE. Management of Primary and Secondary Invasive Mycoses. Pharmacotherapy Self-Assessment Program (PSAP). American College of Clinical Pharmacy 2005.

32. Lewis RE, Raad II. Treatment Approaches for Catheter-Related Infections In: Biofilm Infections: Role of Antibiotic Tolerance and Resistance Marcel Dekker, Inc.

33. Klepser ME, Lewis RE. Antifungal Pharmacodynamics. In: Antimicrobial Pharmacodynamics in Theory and Practice. CH Nightingale, T Murakawa, PG Ambrose (ed.). Marcel Dekker, Inc., New York, New York. 2001.

34. Lewis RE, Prince RA. Pharmacokinetic and pharmacodynamic principles of antimicrobial dosing in the neutropenic host. In: Febrile Neutropenia. Rubenstein E, Rolston KVI eds. Martin Dunitz, London. 2001

## Book Translation Editor
Hematology: Pathophysiology, Diagnosis and Treatment (Lingua inglese). S. Tura, M. Cavo, P. Zinzani. 1st edition.

## Conference abstracts/posters

1. Lewis RE, Miller G, Reichly R, Schaiff RS, Hall T. Drug usage evaluation of G-CSF and GM-CSF at a tertiary care medical center. 1996\. ASHP Midyear Clinical Meeting. New Orleans, LA December 1996.

2. Klepser ME, Ernst EJ, Ernst ME, Lewis RE, Pfaller MA. Antifungal time-kill curves, influence of test conditions on results. 37<sup>th</sup> Interscience Conference on Antimicrobial Agents and Chemotherapy, 1997. Toronto, Ontario, Canada

3. Klepser ME, Ernst EJ, Biedenbach D, Lewis RE, Lund BC, Jones RN. Evaluation of low-dose, extended interval clindamycin regimens against _Staphylococcus aureus_ and _Streptococcus pneumoniae_ using a dynamic in vitro model of infection. American College of Clinical Pharmacy 1997 Annual Meeting. Phoenix, AZ.

4. Lund BC, Klepser ME, Ernst EJ, Lewis RE, Pfaller MA. Antifungal activity of fluconazole on _Candida albicans_in an in vitro dynamic model. American College of Clinical Pharmacy 1997 Annual Meeting. Phoenix, AZ.

5. Lewis RE, Klepser ME, Ernst EJ, Yeramian PD, Jones RN. Time-kill analysis of metronidazole activity against _Bacteroides_ spp. and _Clostridium difficile_. American Society for Microbiology. 98<sup>th</sup> General Meeting, 1998. Atlanta, GA.

6. Lewis RE, Klepser ME, Pfaller MA. Evaluation of antifungal activity and the duration of the post-antifungal effect of 5-fluorocytosine monotherapy against pathogenic yeast. 38<sup>th</sup> Interscience Conference on Antimicrobial Agents and Chemotherapy, 1998. San Diego, CA.

7. Lewis RE, Klepser ME, Ernst EJ, Yeramian PD, Jones RN. Comparison of oral immediate-release (IR) and extended release (ER) metronidazole bactericidal activity against _Bacteroides_ spp. using an in vitro model of infection. 38<sup>th</sup> Interscience Conference on Antimicrobial Agents and Chemotherapy, 1998. San Diego, CA.

8. De Lallo VC, Lewis RE, Petzold RC, Pfaller MA, Klepser ME. Evaluation of amphotericin B (AmB) and flucytosine (5-FC) alone, and in combination against _Candida albicans_ and _Cryptococcus neoformans_ using time-kill methodology. American College of Clinical Pharmacy. 1998 Annual Meeting. Cincinnati, OH.

9. Klepser ME, Malone D, Lewis RE, Ernst EJ, Pfaller MA. Evaluation of Voriconazole Pharmacodynamics Using Time-kill Methodology. Conference on Antimicrobial Agents and Chemotherapy, 1999. San Diego, CA.

10. Lewis RE, Klepser ME, Piscitelli SC, Groll A, De Lallo VC, Quintiliani R, Ernst EJ, Walsh T J, Pfaller MA. In vivo tissue activity of high-dose liposomal amphotericin B (AmBisome) in a neutropenic murine candidal thigh infection model. 39<sup>th</sup> Interscience Conference on Antimicrobial Agents and Chemotherapy, 1999. San Diego, CA.

11. Lewis RE, Diekema DJ, Messer SA, Pfaller MA, Klepser ME. Comparison of Etest, checkerboard dilution, and time-Kill testing for the detection of synergy or antagonism among Candida spp. 39<sup>th</sup> Interscience Conference on Antimicrobial Agents and Chemotherapy, 1999. San Diego, CA.

12. Klepser ME, Lewis RE, Ernst EJ, Pfaller MA, Society of Infectious Disease Pharmacists. Multicenter evaluation of standardized methods for conducting antifungal time-kill studies. 39<sup>th</sup> Interscience Conference on Antimicrobial Agents and Chemotherapy, 1999. San Diego, CA.

13. Lewis RE, Turley JC. Susceptibility of community-acquired respiratory tract pathogens collected in Texas during 1998-1999: Analysis of Texas Data from the Cast Study. 38<sup>th</sup> Infectious Disease Society of America. 2000 New Orleans, LA

14. Rogers DP, Lewis RE, Chapman S. Antifungal activity of amphotericin B is not calcium dependent. 40<sup>th</sup> Interscience Conference on Antimicrobial Agents and Chemotherapy, 2000. Toronto, ONT

15. Lewis RE, Prince RA, Kontoyiannis DP. Pretreatment with Itraconazole Attenuates the Efficacy of Increasing Amphotericin B Dosages in a Murine Model of Invasive Pulmonary Aspergillosis. Platform Presentation-Animal Models of Infection Session. 41<sup>st</sup> Interscience Conference on Antimicrobial Agents and Chemotherapy, 2001. Chicago, IL.

16. Lewis, RE, Kontoyiannis DP, Dariouche RH, Raad II, and Prince RA. Antifungal activity of amphotericin B, fluconazole, and voriconazole in an in vitro model of Candida catheter-related bloodstream infection. 41<sup>st</sup> Interscience Conference on Antimicrobial Agents and Chemotherapy, 2001. Chicago, IL.

17. Lewis RE, Lo HJ, Raad II, and Kontoyiannis, DP. Lack of catheter colonization by the _cph1/cph1 efg1/efg1_double null mutant, a _C. albicans_ strain that is defective in filamentous growth. 41<sup>st</sup> Interscience Conference on Antimicrobial Agents and Chemotherapy, 2001. Chicago, IL.

18. Kontoyiannis DP, Reddy BT, Bodey GP, Luna M, Lewis RE, Tarrand J, Raad II. Pulmonary Candidiasis in Cancer Patients: An autopsy study. Platform presentation. 41<sup>st</sup> Interscience Conference on Antimicrobial Agents and Chemotherapy, 2001. Chicago, IL

19. Kontoyiannis DP, Osherov N, Lewis, RE, Albert ND, May G. L-685, 818, an non-immunosuppressive calcineurin inhibitor enhances the activity of caspofungin (CAS) against _Aspergillus fumigatus_. 41<sup>st</sup> Interscience Conference on Antimicrobial Agents and Chemotherapy, 2001. Chicago, IL.

20. Lewis RE, Neuhauser MN, Tarrand J, Kontoyiannis, DP. Species Distribution and Antifungal Susceptibility of _Candida_ Isolates from an Oncology-Specialty Hospital. American College of Clinical Pharmacy. 2001. Annual Meeting. Tampa, FL.

21. Coyle E, RE Lewis, RA Prince. Activity of TMP/SMX against _Stenotrophomonas maltophilia_ in a _in vitro_ pharmacodynamics infection model. Infectious Diseases Society of America, 2001, San Francisco, CA.

22. Lewis RE, H.A. Torres, G.S. May, I.I. Raad, J. Thornby, K.V.I. Rolston, D. Upadhyaya, G. P. Bodey, D. P. Kontoyiannis. In vitro susceptibility and tolerance of _Aspergillus_ species in a tertiary care cancer center: Correlation with invasive aspergillosis (IA) and its outcome. 42nd Interscience Conference on Antimicrobial Agents and Chemotherapy, 2002, San Diego, CA.

23. Liu W, RE Lewis, GS May, D. P. Kontoyiannis. Preexposure of _A. fumigatus_ to fluconazole induces tolerance to itraconazole _in vitro_. 42nd Interscience Conference on Antimicrobial Agents and Chemotherapy, 2002,San Diego, CA.

24. DP Kontoyiannis, GS May, RE Lewis, ND Albert, RA Prade. Deletion of the _hog_A gene, an osmotic stress regulator, results in hypersensitivity to caspofungin in the model mould _A. nidulans_. 42nd Interscience Conference on Antimicrobial Agents and Chemotherapy, 2002, San Diego, CA.

25. DP Kontoyiannis, R. Hachem, RE Lewis, G. Rivero, H. Kantarjian, II Raad. Efficacy and toxicity of caspofungin/liposomal amphotericin B combination (platform presentation). 42nd Interscience Conference on Antimicrobial Agents and Chemotherapy, 2002, San Diego, CA.

26. DP Kontoyiannis, RE Lewis, GS May, ND Albert, II Raad. Sequential exposure of _A. fumigatus_ to itraconazole and caspofungin:Evidence of enhanced in vitro activity of this combination. 42nd Interscience Conference on Antimicrobial Agents and Chemotherapy, 2002, San Diego, CA.

27. Antoniadou A, Torres HA, RE Lewis, II Raad, J Thornby, J Tarrand, KVI Rolston, X Han, GP Bodey, DP Kontoyiannis. Bloodstream candidiasis in cancer patients. 42nd Interscience Conf. on Antimicrobial Agents and Chemotherapy, 2002, San Diego, CA.

28. Coyle E, RE Lewis, J Chi, KVI Rolston, RA Prince. Varying Doses of Levofloxacin and the Corresponding Relationship of Antimicrobial Activity and Resistance Selection against Pseudomonas aeruginosa. (Platform presentation) 42nd Interscience Conference on Antimicrobial Agents and Chemotherapy, 2002, San Diego, CA.

29. Healy M, Reece K., Lewis RE, Kontoyiannis DP. Molecular Fingerprinting of _Candida_ and _Aspergillus_ species by automated rep-PCR. American Society for Microbiology 103<sup>rd</sup> General Meeting, 2003, Washington, D.C.

30. RE Lewis, J. Chi, N. P. Wiederhold, D. P. Kontoyiannis, X. Han, R. A. Prince. Detection of gliotoxin, an immunologically-active metabolite secreted by _Aspergillus fumigatus,_ in animals and humans with invasive aspergillosis. 43rd Interscience Conference on Antimicrobial Agents and Chemotherapy, 2003, Chicago, IL.

31. NP Wiederhold, Chi J, Kontoyiannis DP, Prince RA, Lewis RE. In vitro reduction of the Aspergillus fumigatus metabolite gliotoxin by amphotericin B, caspofungin, and voriconazole. 43rd Interscience Conference on Antimicrobial Agents and Chemotherapy, 2003, Chicago, IL.

32. NP Wiederhold, DP Kontoyiannis, J Chi, RA Prince, VH Tam, RE Lewis. In vivo pharmacodynamics of caspofungin in a murine model of invasive pulmonary aspergillosis. 43rd Interscience Conference on Antimicrobial Agents and Chemotherapy, 2003, Chicago, IL. Platform presentation.

33. NP Wiederhold, DP Kontoyiannis, RE Lewis. In vitro pharmacodynamics of rapid vs continuous infusion amphotericin B deoxycholate in the presence of human serum albumin. 43rd Interscience Conference on Antimicrobial Agents and Chemotherapy, 2003, Chicago, IL.

34. Hend HA, Chatzinikolaou, Alakech B, Hachem R, Lewis RE, Kontoyiannis DP, Tarrand JT, Raad IR. Differential positive quantitative blood cultures and the diagnosis of catheter related bloodstream infections. 43rd Interscience Conference on Antimicrobial Agents and Chemotherapy, 2003, Chicago, IL.

35. MS Lionakis, RE Lewis, HA Torres, KVI Rolston, II Raad, DP Kontoyiannis. In vitro susceptibility of Aspergillus clinical isolates to AMB, ITZ and VRC by E-test and the effect of prior antifungal exposure. 43rd Interscience Conference on Antimicrobial Agents and Chemotherapy, 2003, Chicago, IL.

36. RE Lewis, NP Wiederhold, ME Klepser. In vitro pharmacodynamics of amphotericin B, itraconazole and voriuconazole against Aspergillus, Fusarium and Scedosporium spp. 43rd Interscience Conference on Antimicrobial Agents and Chemotherapy, 2003, Chicago, IL.

37. MS Lionakis, Lahdenranta J, Liu W, RE Lewis, R Pasqualini, W. Arap, DP Kontoyiannis. Biopanning as an approach to study the pathogenesis of invasive aspergillosis. 43rd Interscience Conference on Antimicrobial Agents and Chemotherapy, 2003, Chicago, IL

38. MS Lionakis, G. Halder, RE Lewis, GS May, ND Albert, DP Kontoyiannis . A non-vertebrate in vivo model to study invasive aspergillosis and its treatment with oral antifungals: early experience with _Drospohila_. 43rd Interscience Conference on Antimicrobial Agents and Chemotherapy, 2003, Chicago, IL. Platform presentation.

39. MS Lionakis, RE Lewis, DP Kontoyiannis. Pentamidine is active in vitro against Fusarium species. 43rd Interscience Conference on Antimicrobial Agents and Chemotherapy, 2003, Chicago, IL.

40. MS Lionakis, RE Lewis, HA Torres, KVI Rolston, II Raad, DP Kontoyiannis. Comparison of the in vitro activities of modern antifungals against Aspergillus isolates from cancer patients. 43rd Interscience Conference on Antimicrobial Agents and Chemotherapy, 2003, Chicago, IL.

41. KW Garey, MM Neuhauser, DT Bearden, JP Cannon, RE Lewis, LO Gentry, DP Kontoyiannis Evaluation of antifungal usage in SICU patients: A multi-institutional study. 43rd Interscience Conference on Antimicrobial Agents and Chemotherapy, 2003, Chicago, IL. Platform presentation.

42. Wiederhold NP, Lewis RE, Raad, II, Coyle EA, Prince RA. Comparaison of linezolid vs. vancomycin in a simulated model of catheter-related bloodstream infections. 43rd Interscience Conference on Antimicrobial Agents and Chemotherapy, 2003, Chicago, IL.

43. VH Tam, An Shilling, RE Lewis, DA Melnick, and AN Boucher. A novel approach for studying the combined pharmacodynamics of antibacterial agents. 43rd Interscience Conference on Antimicrobial Agents and Chemotherapy, 2003, Chicago, IL.

44. Segal, B. Bernacki, W. Slocum H., Pera, P., D. Carly. Lewis R. E. Combination antifungal therapy with micafungin (Mica) and amphotericin B desoxycholate (Amb-d) prolongs survival in the p47phox-deficient mouse model of chronic granulomatous disease (CGD) with experimental pulmonary aspergillosis. 12<sup>th</sup> Annual Focus on Fungal Infection, New Orleans, LA.

45. Lewis RE, NP Wiederhold, MS Lionakis, J Chi, , RA Prince, DP Kontoyiannis. Frequency and Distribution of Gliotoxin (GT)-Producing _Aspergillus_ Isolates Recovered from Patients at a Tertiary Care Cancer Center. 44th Interscience Conference on Antimicrobial Agents and Chemotherapy, 2004, Washington, D.C.

46. M. S. Lionakis, G. Halder, R. E. Lewis, N. P. Wiederhold, D. P. Kontoyiannis. Efficacy of Voriconazole in Experimental Aspergillosis in _Drosophila_. 44th Interscience Conference on Antimicrobial Agents and Chemotherapy, 2004, Washington, D.C. Platform presentation.

47. M. S. Lionakis, G. Halder, R E Lewis, N. P. Wiederhold, G. S. May, D. P. Kontoyiannis. Experimental Aspergillosis in _Drosophila_: Influence of Mode of Infection on _Aspergillus_ Virulence. 44th Interscience Conference on Antimicrobial Agents and Chemotherapy, 2004, Washington, D.C.

48. Wiederhold NP, Kontoyiannis DP, Lewis RE. Eagle-like effect of caspofungin (CAS) against _Candida_ and _Aspergillus_ spp.; Association with homeostatic mechanisms of cell-wall integrity. 44th Interscience Conference on Antimicrobial Agents and Chemotherapy, 2004, Washington, D.C. Platform Presentation.

49.  Wiederhold NP, Kontoyiannis DP, Lewis RE. Relationship between interferon gamma/ Interleukin-10 and mycological efficacy of amphotericin B in invasive pulmonary aspergilloisis. 44th Interscience Conference on Antimicrobial Agents and Chemotherapy, 2004, Washington, D.C.

50. DP. Kontoyiannis, M. S. Lionakis , R. E. Lewis, M. Healy , G. Chamilos, G. P. Bodey, C. Perego , Safdar A, Kantarjian H, Champlin R , T. J. Walsh , I. I. Raad. Zygomycosis in the era of _Aspergillus_-Active Antifungal Therapy in a Tertiary Care Cancer Center: A Case Control Observational Study of 27 Recent Cases. 44th Interscience Conference on Antimicrobial Agents and Chemotherapy, 2004, Washington, D.C. Platform Presentation.

51. G. Chamilos, R.E. Lewis, D.P. Kontoyiannis. The Unique Alternative Mitochondria Susceptibility to Caspofungin (CAS). 45<sup>th</sup> Interscience Conference on Antimicrobial Agents and Chemotherapy. Washington, DC. Abstract 842.

52. G. Chamilos, R. E. Lewis, M. S. Lionakis, G. Halder, D.P. Kontoyiannis. Experimental zygomycosis in _Drosophila melanogaster_. 45<sup>th</sup> Interscience Conference on Antimicrobial Agents and Chemotherapy. Washington, DC. Abstract 1198.

53. G. Chamilos, M. Luna, R. E. Lewis, A. Safdar, G. P. Bodey, I. I. Raad, D. P. Kontoyiannis. Invasive Fungal Infections An Autopsy Study. 45<sup>th</sup> Interscience Conference on Antimicrobial Agents and Chemotherapy. Washington, DC. Abstract 996. Platform presentation.

54. G. Chamilos, R. E. Lewis, D. P. Kontoyiannis. Lovastatin has Significant Activity against _Zygomycetes In vitro_ and _In vivo_ and shows _In vitro_ Synergy with Voriconazole. 45<sup>th</sup> Interscience Conference on Antimicrobial Agents and Chemotherapy. Washington, DC. Abstract 768.

55. R.E. Lewis, D. P. Kontoyiannis. Micafungin (MICA) In Combination With Voriconazole (VRC) In Aspergillus Species: A Pharmacodynamic Approach For Detection Of Synergy In Vitro. 45<sup>th</sup> Interscience Conference on Antimicrobial Agents and Chemotherapy. Washington, DC. Abstract 1083.

56. Tam VH, A.N. Schilling, A.L. Kwa, N.P. Wiederhold, R.E. Lewis. Pharmacodynamics (PD) of Polymyxin B (PB) against Multi-drug Resistant (MDR) _Pseudomonas aeruginosa_ (PA). 44th Interscience Conference on Antimicrobial Agents and Chemotherapy, 2004, Washington, D.C.

57. R.E. Lewis, Singh N, Limaye A, Husain S, Safdar N, Munoz P, Pursell K, Kontoyiannis D. Detection Of Synergy By XTT-Enhanced Checkerboard Dilution Testing Of Aspergillus: Correlation With Outcome In Patients With Invasive Aspergillosis Treated With Combination Voriconazole (VRC) and Caspofungin (CAS) Therapy. 45<sup>th</sup> Interscience Conference on Antimicrobial Agents and Chemotherapy. Washington, DC. Abstract 1053.

58. G. Chamilos, R.E. Lewis, R.A. Prince, and D.P. Kontoyiannis. Zygomycetes Hyphae Are Less Susceptible To Killing By Polymorphonuclear Neutrophils (PMNs) Than _Aspergillus_ Hyphae_,_ Through Toll-like Receptor (TLR) Independent Mechanisms. 45<sup>th</sup> Interscience Conference on Antimicrobial Agents and Chemotherapy. Washington, DC. Abstract 1232.

59. G. Chamilos, R.E. Lewis, D.P. Kontoyiannis. The Unique Alternative Mitochondria Susceptibility to Caspofungin (CAS). 45<sup>th</sup> Interscience Conference on Antimicrobial Agents and Chemotherapy. Washington, DC. Abstract 842.

60. G. Chamilos, R. E. Lewis, M. S. Lionakis, G. Halder, D.P. Kontoyiannis. Experimental zygomycosis in _Drosophila melanogaster_. 45<sup>th</sup> Interscience Conference on Antimicrobial Agents and Chemotherapy. Washington, DC. Abstract 1198.

61. G. Chamilos, M. Luna, R. E. Lewis, A. Safdar, G. P. Bodey, I. I. Raad, D. P. Kontoyiannis. Invasive Fungal Infections An Autopsy Study. 45<sup>th</sup> Interscience Conference on Antimicrobial Agents and Chemotherapy. New Orleans, LA. Abstract 996\. Platform presentation.

62. G. Chamilos, R. E. Lewis, D. P. Kontoyiannis. Lovastatin has Significant Activity against _Zygomycetes In vitro_ and _In vivo_ and shows _In vitro_ Synergy with Voriconazole. 45<sup>th</sup> Interscience Conference on Antimicrobial Agents and Chemotherapy. Washington, DC . Abstract 768.

63. R.E. Lewis, D. P. Kontoyiannis. Micafungin (MICA) In Combination With Voriconazole (VRC) In Aspergillus Species: A Pharmacodynamic Approach For Detection Of Synergy In Vitro. 45<sup>th</sup> Interscience Conference on Antimicrobial Agents and Chemotherapy. Washington, DC Abstract 1083.

64. R.E. Lewis, G. Chamilos, K.V. Komanduri, R. A, Prince, D.P. Kontoyiannis. Liposomal Amphotericin B (L-AMB) is Superior to Amphotericin B Deoxycholate (AMB-d) in Reducing Inflammatory Lung Injury (ILI) and Fungal Burden in Corticosteroid-Treated Mice with Invasive Pulmonary Aspergillosis (IPA). 45<sup>th</sup> Interscience Conference on Antimicrobial Agents and Chemotherapy. Washington, DC. Abstract 1028.

65. R.E. Lewis, G. Chamilos, D.P. Kontoyiannis, R. A. Prince. Pseudomonas aeruginosa (PSA) Attenuates Human Neutrophil killing of Aspergillus fumigatus (AF) Hyphae. 45<sup>th</sup> Interscience Conference on Antimicrobial Agents and Chemotherapy. Washington, DC. Abstract 1082.

66. D.P. Kontoyiannis, G. Chamilos, R.E. Lewis, J.A. Tarrand. Increased Culture Recovery of Zygomycetes under Physiologic Temperature Conditions. 43<sup>rd</sup> Infectious Disease Society of America, San Francisco, CA. Abstract 797.

67. RE Lewis, G Chamilos, RA Prince, D Kontoyiannis Empty liposomes reduce inflammatory lung injury and boost PMN fungal clearance in a corticosteroid-immunosuppressed murine model of acute invasive pulmonary aspergillosis. 46<sup>th</sup> Interscience Conference on Antimicrobial Agents and Chemotherapy. San Francisco, CA. Abstract 1686. Platform presentation.

68. RE Lewis, Guanling Liao, Jinggou Hou, G Chamilos, RA Prince, DP Kontoyiannis. Comparative analysis of amphotericin B lipid complex (ABLC) and lipsomal amphotericin B (L-AMB) Kinetics of Lung Accumulation and Fungal Clearance in a Murine Model of Acute Invasive Pulmonary Aspergillosis. 46<sup>th</sup> Interscience Conference on Antimicrobial Agents and Chemotherapy. San Francisco, CA. Abstract 1689. Platform presentation.

69. Chamilos G, Lewis RE, Albert ND, Kontoyiannis DP. Genome-wide screening for Genes Associated with Increased gliotoxin sensitivity in _Saccharomyces cerevisiae_. 46<sup>th</sup> Interscience Conference on Antimicrobial Agents and Chemotherapy. San Francisco, CA. Abstract 1782.

70. Bhatti, Z, Dennis C, FEminella J, Brun Y, Almyroudis NG, Lewis RE, Hollad S, Petraitiene R, Walsh TJ, Segal B. Host defense against spergillosis in the p47_phox-_/- mouse model of chronic granulomatous disease. 46<sup>th</sup> Interscience Conference on Antimicrobial Agents and Chemotherapy. San Francisco, CA. Abstract 1683.

71. Chamilos G, Lewis RE, Kontoyiannis DP. Dissecting the molecular aspects of immunopathogenisis of zygomycosis in _Drosophila melanongaster_. 46<sup>th</sup> Interscience Conference on Antimicrobial Agents and Chemotherapy. San Francisco, CA. Abstract 1330.

72. DP Kontoyiannis, G Chamilos, Lewis RE, Manning J,Raad I, Han X. Increased bone marrow iron stores are an independent risk factor for invasive aspergillosis in severely immunocompromised cancer patients: A case control observational study. 46<sup>th</sup> Interscience Conference on Antimicrobial Agents and Chemotherapy. San Francisco, CA. Abstract 0295.

73. GA Lamaris, Chamiols G, Lewis RE, Raad I, Kontoyiannis DP. Scedosporiosis in a tertiary care cacner center in the past 16 years. 46<sup>th</sup> Interscience Conference on Antimicrobial Agents and Chemotherapy. San Francisco, CA. Abstract 1428.

74.  Chamilos G, Lewis RE, Lanaris G, Walsh TJ, Kontoyiannis DP. Rhizopus hyphae trigger an early proinflammatory response in human PMNs by selective activation of TLR 2\. 46<sup>th</sup> Interscience Conference on Antimicrobial Agents and Chemotherapy. San Francisco, CA. Abstract 1332.

75. Chamilos G, Lewis RE, Raad I, Kontoyiannis DP. Epidemiology and outcome of invasive zygomycosis in a tertiary care cancer center (1989-2006): A retrospective study of 95 episodes. 46<sup>th</sup> Interscience Conference on Antimicrobial Agents and Chemotherapy. San Francisco, CA. Abstract 0890.

76. Kontoyiannis DP, Chamilos G, Lewis RE, Manning J, Raad II, Han X. Increased bone marrow iron stores are an independent risk factor for invasive aspergillosis in severely immunocompromised patients: A case control study. 46<sup>th</sup> Interscience Conference on Antimicrobial Agents and Chemotherapy. San Francisco, CA. Abstract 034.

77. Lewis RE. What pharmacodynamics have taught us about treating fungal pneumonia: are we giving enough? 46<sup>th</sup> Interscience Conference on Antimicrobial Agents and Chemotherapy. San Francisco, CA. Abstract M-0574.

78. Lewis R.E. Evaluating the Activity of Antifungal Agents In Vitro and In Vivo: Beyond Broth Microdilution. 47<sup>th</sup> Interscience Conference on Antimicrobial Agents and Chemotherapy. Chicago, IL

79. Chamilos G., Lewis R.E., Kontoyiannis D.P. Delaying Amphotericin B (AMB)-Based Frontline Therapy Significantly Increases Mortality in Hematologic Malignancy (HM) Patients (pts) with Zygomycosis (Z). 47<sup>th</sup> Interscience Conference on Antimicrobial Agents and Chemotherapy. Chicago, IL. Abstract M-619.

80. G Chamilos, Cj Nobile, Vm Bruno, RE Lewis, AP Mithcell, DP Kontoyiannis. A Novel _Candida albicans_ Transcriptional Regulator of Cell Wall Integrity Identified Through a Screen in Toll Deficient (_Tl_) Flies, Promotes Virulence in Mammals. 47<sup>th</sup> Interscience Conference on Antimicrobial Agents and Chemotherapy. Chicago, IL. Abstract B-1446.

81. GA Lamaris, RE Lewis, DP Kontoyiannis. Voriconazole (VRC) is Effective against Posaconazole (POSA)- Preexposed _Aspergillus fumigatus_ (AF) in Experimental Aspergillosis in Flies. 47<sup>th</sup> Interscience Conference on Antimicrobial Agents and Chemotherapy. Chicago, IL. Abstract B-1451.

82. DP Kontoyiannis, R. Lewis <sup>1</sup>, O. Lortholory <sup>2</sup>, N. Singh<sup>3</sup>, And Crypto Tx Study Gp; Interactions between Immunosuppressants and Antifungals against _C. neoformans_ (_C.n_) and their Correlation with Outcomes in Solid Organ Transplant (SOT) Patients (pts) with Cryptococcosis. 47<sup>th</sup> Interscience Conference on Antimicrobial Agents and Chemotherapy. Chicago, IL. Abstract M-1850.

83. RE Lewis, ND Albert, DP Kontoyiannis. Comparison of the Dose-Dependent Activity and Paradoxical Effect of Caspofungin (CAS) and Micafungin (MICA) in a Neutropenic Murine Model of Invasive Pulmonary Aspergillosis (IPA). 47<sup>th</sup> Interscience Conference on Antimicrobial Agents and Chemotherapy. Chicago, IL. Abstract M-1824.

84. Lamaris G, Lewis RE, Kontoyiannis DP. Voriconazole (VRC) Pre-Exposed _Rhizopus oryzae (Rh.o)_ has Increased Virulence in Experimental Zygomycosis in Flies and Mice. 47<sup>th</sup> Interscience Conference on Antimicrobial Agents and Chemotherapy. Chicago, IL. Abstract B-1449.

85. Lamaris G, Lewis RE, Chamilos G, Kontoyiannis DP. Caspofungin (CAS) Mediated Beta-Glucan (BG) Unmasking and Enhancement of Human Neutrophil (PMN) Activity against _Aspergillus_ spp. 47<sup>th</sup> Interscience Conference on Antimicrobial Agents and Chemotherapy. Chicago, IL. Abstract M-1857.

86. G. Lamaris, RE Lewis, G. Chamilos, Dp Kontoyiannis. Caspofungin (CAS) Mediated Beta-Glucan Unmasking and Enhancement of Neutrophil (PMN) Activity against Non-_Aspergillus_ Moulds. 47<sup>th</sup> Interscience Conference on Antimicrobial Agents and Chemotherapy. Chicago, IL.

87. RE Lewis, G. Chamilos, ND Albert, D Kontoyianis.;Efficacy of Single-Dose Liposomal Amphotericin B (L-AMB) or Micafungin (MICA) Prophylaxis in a Persistently Neutropenic Murine Model of Invasive Pulmonary Aspergillosis (IPA). 47<sup>th</sup> Interscience Conference on Antimicrobial Agents and Chemotherapy. Chicago, IL.

88. Kofteridis D, Lewis RE, Kontoyiannis DP. Caspofungin non-susceptible _Candida_ spp isolates in cancer patients. 19<sup>th</sup> European congress of Clinical Microbiology and Infectious diseases (ECCMID). Helsinki, Finland, 05/2009.

89. Pongas GN, Lewis RE, Kontoyiannis DP. _Aspergillus fumigatus_ – _Pseudomonas aeruginosa_: Friends or foes? 49<sup>th</sup> Annual ICAAC meeting, San Francisco, CA, 9/2009.

90. Ben-Ami R, Lewis RE, Leventakos K, Latge JP, Kontoyiannis DP. The importance of catalases for _Aspergillus fumigatus_ virulence determined in a cutaneous model system. 49<sup>th</sup> Annual ICAAC meeting, San Francisco, CA, 9/2009.

91. Campo M, Lewis RE, Kontoyiannis DP. Invasive Fusariosis in Patients with Hematologic Malignancy at MD Anderson Cancer Center: The Last Decade. 47th Annual Meeting of the Infectious Diseases Society of America (IDSA), Philadelphia, PA, 10/2009.

92. Best L, Singh N, Ben-Ami R, Albert N, Raad II, Lewis RE, Kontoyiannis DP. In Vitro Interactions of Tacrolimus with Posaconazole or Caspofungin against Zygomycetes, Annual Meeting of the Infectious Diseases Society of America (IDSA), Philadelphia, PA, 10/2009.

93. Leventakos K, Lewis RE, Kontoyiannis DP. Posaconazole (POS) Plasma Concentrations in Hematological Malignancy (HM) Patients without Mucositis or Gut GVHD. 49<sup>th</sup> Annual ICAAC meeting, San Francisco, CA, 9/2009.

94. Leventakos K, Lewis RE, Kontoyiannis DP. Effect of low-dose caspofungin in a neutropenic and steroid- treated murine model of pulmonary mucromycosis. 49<sup>th</sup> Annual ICAAC meeting, San Francisco, CA, 9/2009

95. Watson CC, Ben-Ami R, Lewis RE, Arias C Raad II, Kontoyiannis DP. A study of the role of panton-valentine leukocidin in mrsa virulence using wild-type and toll-deficient _drosophila melanogaster_. 49<sup>th</sup> Annual ICAAC meeting, San Francisco, CA, 9/2009.

96. Ben-Ami R, Lewis RE, Leventakos K, Kontoyiannis DP. _Aspergillus fumigatus_ inhibits angiogenesis through the production of gliotoxin and other secondary metabolites. 49<sup>th</sup> Annual ICAAC meeting, San Francisco, CA, 9/2009.

97. Ben-Ami R, Garcia-Effron G, Lewis RE, Leventakos K, Perlin DS, Kontoyiannis DP. Mutations in _Candida albicans_ FKS1 conferring echinocandin resistance are associated with attenuated virulence. 49<sup>th</sup> Annual ICAAC meeting, San Francisco, CA, 9/2009.

98. Watson C, Ben-Ami R, Arias C, Raad II, Lewis RE, Kontoyiannis DP. A study of the panton-velentine leukocidin in methicillin resistant Staphylococcus aureus virulence using wild-type and toll-deficient Drosophila melanogaster. Platform presentation. 47<sup>th</sup> Infectious Diseases Society of America (IDSA) Meeting, Philadelphia, PA, 2010.

99.  Best L, Singh N, Ben-Ami R, Raad II, Lewis RE, Konotyiannis DP. In vitro interactions of tacrolimus with posaconazole or caspofungin against zygomycetes. 47<sup>th</sup> Infectious Diseases Society of America (IDSA) Meeting, Philadelphia, PA, 2010.

100. Campo M, Lewis RE, Kontoyiannis DP. Invasive fusariosis in patients with hematologic malignancy at M.D. Anderson Cancer Center. 47<sup>th</sup> Infectious Diseases Society of America (IDSA) Meeting, Philadelphia, PA, 2010.

101. Leventakos K, Lewis RE, Chamilos G, Tamboli P, Raad II, Luna M, Kontoyiannis DP. Trends in epidemiology and sites of involvement by invasive fungal infections in patients with hematologic malignacies: a 20 year autopsy study. 47<sup>th</sup> Infectious Diseases Society of America (IDSA) Meeting, Philadelphia, PA 2010.

102. Lewis RE, G Liao, Wang W, Prince RA, Kontoyiannis DP. Comparative in vivo selection for breakthrough mucormycisis of antifungals used to treat invasive pulmonary aspergillosis. 4<sup>th</sup> Advances Against Aspergillosis Meeting, Rome, Italy 2010.

103. Lewis RE, ND Albert, G. Lia, Wang W, Prince RA, Kontoyiannis DP. Efficacy of dosage escalation strategies for liposomal amphotericin B in the treatment of experimental _Aspergillus terreus_ pneumonia. 4<sup>th</sup> Advances Against Aspergillosis Meeting, Rome, Italy 2010.

104. Perez C, Tam VH, Ledesma K, Abdelraouf K, Kontoyiannis DP, Lewis RE. Comparative immunoprofiling of multidrug resistant (MDR) _P. aeruginosa_. 50<sup>th</sup> Interscience Conference on Antimicrobial Agents Chemotherapy, Boston, MA 2011.

105.  Sampsonas F, Lewis RE, Kontoyiannis DP. Risk stratification for early mortality in patients with hematologic cancer and invasive pulmomary mucormycosis. 50<sup>th</sup> Interscience Conference on Antimicrobial Agents Chemotherapy, Boston, MA 2011.

106. Lewis RE, G. Liao, Kontoyiannis DP. Use of a murine macrophage reporter cell assay to characterize the immunopharmacodynamics of caspofungin against _Aspergillus fumigatus_. 50<sup>th</sup> Interscience Conference on Antimicrobial Agents Chemotherapy, Boston, MA 2011.

107.  Ben-Ami, Lewis RE, Perlin D, Kontoyiannis DP. Candida albicans FKS1 hot spot mutations associated with echinocandin resistance affect biofilm formation. 50<sup>th</sup> Interscience Conference on Antimicrobial Agents Chemotherapy, Boston, MA 2011.

108.  Pongas GN, Lewis RE, Walsh TJ, Kontoyiannis DP. Activity of deferasirox against Mucorales: Influence of species, exogenous iron and sub-ceullular compartment. 50<sup>th</sup> Interscience Conference on Antimicrobial Agents Chemotherapy, Boston, MA. 2011.

109.  Pongas GN, Lewis RE, Kontoyiannis DP. Invasive mould infections in pediatric cancer patients: a single institution, 10-year retrospective study. 48<sup>th</sup> Infectious Disease Society of America (IDSA) Meeting, Vancouver, BC, Canada 2011.

110.  Ben- Ami R, Lewis RE, Kontoyiannis DP. In vitro interactions among echinocandins against _Aspergillus fumigatus_: Lack of concordance among methods. 48<sup>th</sup> Infectious Disease Society of America (IDSA) Meeting, Vancouver, BC, Canada 2011.

111.  Stanzani M, Lewis RE, Fiacchini M<sup>,</sup> Ricci P, Tumietto F, Viale P, Ambretti S, Baccarani M, and Vianelli N. Development and validation of a risk-based score for invasive mold disease in patients with hematological malignancies. 17th International Meeting of the Immunocompromised Host Society. Platform presentation. Genoa, Italy. 2012.

112.  Girometti N, Lewis RE, Tumietto F, Ambretti S, Viale P. Bacteremia with _Klebsiella penumoniae_ carbapenemase (KPC)-Producing Organisms: Ana analysis of attributable mortality and risk factors for recurrance. Abstract B-2333. 52<sup>nd</sup> Interscience Conference on Antimicrobial Agents Chemotherapy, San Francisco, CA. 2012.

113.  Lewis RE, Sampsonis F, Georgiadou S, Chamilos G, Kontoyiannis DP. Absolute lymphocyte count as a prognostic marker for early mortality in hematological malignancy patients with pulmonary mucormycosis.Abstract M-1994\. 52<sup>nd</sup> Interscience Conference on Antimicrobial Agents Chemotherapy, San Francisco, CA. 2012.

114.  Lewis RE, Liao G, Young K, Douglas C, Kontoyiannis DP. In vitro immunopharmacodynamics of cell-wall active antifungals against _Candida albicans_ and _Aspergillus fumigatus_. Abstract M-1102\. 52<sup>nd</sup> Interscience Conference on Antimicrobial Agents Chemotherapy, San Francisco, CA. 2012

115.  Lewis RE, Liao G, Young K, Douglas C, Konotyiannis DP. Conditional expression of cell-wall polysaccharide- encoding genes in _C. albicans_ and _A. fumigatus_ reproduces immunopharmacologic effects of caspofungin and nikkomycin Z exposure. Abstract M-1105\. 52<sup>nd</sup> Interscience Conference on Antimicrobial Agents Chemotherapy, San Francisco, CA. 2012.

116.  Lewis RE, Stanzani M, Ambretti S, Viale P, Vianelli N. Prospective cross-sectional observational study of documented infections in patients with hematological malignancies. Abstract P-2124. 23rd European Congress of Clinical Microbiology and Infectious Diseases. Berlin, Germany.

117.  Bartoletti M, Girometti N, Lewis RE, Tumietto F, Cristini F, Ambretti S, Tedeschi S, Ciliberti MF, Lauria D, Finzi G, Viale P. Prospective, Cross-Sectional Observational Study of Hospitalized Patients Colonized with Carbapenemase-Resistant Klebsiella pneumoniae (CR-KP). Abstract P-968\. _Highlighted E-poster_. 23rd European Congress of Clinical Microbiology and Infectious Diseases. Berlin, Germany.

118.  Bartoletti M, Giannella M, Caraceni P, Domenicali M, Ambretti S, Tedeschi S, Lewis RE, Bernardi M, Viale P. Epidemiology and outcomes of bloodstream infections in patients with liver cirrhosis. 48<sup>th</sup> European Association for Study of the Liver, Amsterdam, NE 2013.

119.  Lewis RE, Albert ND, Konotyiannis DP. Comparison of Posaconazole Pharmacodynamics in Neutropenic Murine Models of Sinopulmonary Aspergillosis and Mucormycosis. Abstract M-733. 53<sup>rd</sup> Interscience Conference on Antimicrobial Agents Chemotherapy, Denver, CO. 2013.

120.  Lewis RE, Stanzani M, Ambretti S, Tedeschi S, Viale P, Cavo M, Vianelli N. Prospective, cross-section observational study of 1,263 infection-related hospital admissions in 787 hematological malignancy patients with fever. Abstract P-1265., 24<sup>th</sup> European Congress on Clinical Microbiology Infectious Diseases, 2104. Barcelona, Spain.

121.  Gaibani P, Lombardo D, Bartoletti M, Tedeschi S, Giannella M, Viale P, Lewis RE, M. Landini. Serum bactericidal assay (SBA) of three antimicrobial combination therapies against KPC-producing K. pneumoniae. Abstract, EP0231\. 26th European Congress of Clinical Microbiology and Infectious Diseases.

122.  Giannella M, Marconi L, Graziano E, Tedeschi S, Bartoletti M, Girometti N, Tumietto F, Cristini F, Ambretti S, Giabiani P, Lewis RE, Viale P. Carbapenem-resistant Klebsiella pneumoniae bacteraemia: recurrence and impact of antibiotic treatment .Abstract 0118..26th European Congress of Clinical Microbiology and Infectious Diseases, Amsterdam, Netherlands.

123.  Bartoletti, M, Giannella M, Lewis RE, Schramm C, Bruns T, Merli M, Cobos-Tigueros N, Paul M, Seminari E, Rodríguez-Baño J, Bouza E, Santiago, Tumbarello M, Burra P, Torrani Cerenzia, Calbo E, Barsic B, Petrosillo, Galan Ladero NM, D'Offizi G, Viale Psd. Bloodstream infection in cirrhotic patients: a prospective multicentre study (bichrome). Abstract 0312.26th European Congress of Clinical Microbiology and Infectious Diseases, Amsterdam, Netherlands.

124.  Bartoletti, M., Tedeschi S, Pascale R, Maraolo A, Palmiero G, Luigi R, Tumietto F, Ambretti S, Cristini F, Lewis RE, Giannella M, Viale P. Does frontline use of tigecycline versus meropenem-based regimens for intra- abdominal infection reduce the risk for carbapenem resistant Klebsiella pneumoniae colonization or Clostridium difficile infection. Abstract S0893. 27th European Congress of Clinical Microbiology and Infectious Diseases, Vienna, Austria.

125.  Giannella M, Paolucci M, Vandi G, Roncarati G, Trapani F, Bartoletti M, Tedeschi S, Campoli C, Ambretti S, Landini M, Lewis RE, Viale P. Potential impact of T2Candida assay on the use of empiric antifungal therapy in patients at high risk for candidaemia/invasive candidiasis: a tool for antifungal stewardship programmes? Abstract P0975; 27th European Congress of Clinical Microbiology and Infectious Diseases 2017, Vienna, Austria.

126.  Giannella M, Campoli C, Gaibani P, Conti M, Tedeschi S, Bartoletti M, Cristini F, Tumietto F, Viale P, Lewis RE. Utility of the serum bactericidal titre assay for monitoring antimicrobial therapy of carbapenem resistant Klebsiella pneumoniae. Abstract P1209. 27<sup>th</sup> European Congress of Clinical Microbiology and Infectious Diseases, 2017. Vienna, Austria.

127.  Paolucci M, Roncarati G, Landini M, Lewis RE. Antifungal susceptibility testing for Candida spp.: agreement between EUCAST reference method and commercial tests. Abstract 0134. 27<sup>th</sup> European Congress of Clinical Microbiology and Infectious Diseases, 2017. Vienna, Austria.

128.  Bartoletti M, Giannella M, Tedeschi S, Lewis RE, Viale P. Continuous infusion of beta-lactam antibiotics in patients with liver cirrhosis and bloodstream infection: results from a prospective, multicentre study. Abstract 0094\. 28<sup>th</sup> European Congress of Clinical Microbiology and Infectious Diseases, 2018. Madrid, Spain.

129.  Lewis RE, Beyda N, Albert ND, Kontoyiannis D. In vitro pharmacodynamics of isavuconazole, voriconazole, and posaconazole against agents of aspergillosis, mucormycosis, phaeohyphomycosis, fusariosis, and scedosporiosis. Abstract 0297\. 28<sup>th</sup> European Congress of Clinical Microbiology and Infectious Diseases, 2018. Madrid, Spain.

130.  Giannella M, Pascale R, Toschi A, Ferraro G, Furii F, Bartoletti M, Tedeschi S, Graziano E, Ambretti S, Lewis RE, Viale P. Impact of treatment duration on the risk of relapse in patients with Escherichia coli bloodstream infection Abstract 01184\. 28<sup>th</sup> European Congress of Clinical Microbiology and Infectious Diseases, 2019, Amsterdam, Netherlands.

131.  Glampedakis E, Cassaing S, Fekkar A, Dannaoui E, Bougnoux M, Bretagne S, Neofytos D, Schreiber P, Hennequin C, Morio F, Shadrivova O, Bongomin F, Fernandez Ruiz M, Bellanger A, Arikan-Akdagli S, Erard V, Aigner M, Paolucci M, Charpentier E, Bonnal C, Brun S, Gabriel F, Riat A, Zbinden R, Le Pape P, Klimko N, Lewis RE, Richardson M, İnkaya A, Coste A, Lamoth F. Invasive aspergillosis due to Aspergillus section Usti: a European multi-centre study. Abstract 01184\. 28<sup>th</sup> European Congress of Clinical Microbiology and Infectious Diseases, 2019, Amsterdam, Netherlands.

132.  Giannella M, Bartoletti M, Campoli C, Rinaldi M, Coladonato S, Pascale R, Tedeschi S, Ambretti S, Cristini F, Siniscalchi A, Bertuzzo V, Morelli M, Cescon M, Pinna A, Lewis RE, Viale P. Carbapenem-resistant Enterobacteriaceae infection risk after liver transplantation: the impact of colonisation. Abstract 01144\. 28<sup>th</sup> European Congress of Clinical Microbiology and Infectious Diseases, 2019, Amsterdam, Netherlands.

133. Stanzani M , Sassi C, Sartor C, Battista G, Coppola P, and Lewis RE. Early Low-Dose Computed Tomography with Pulmonary Angiography to Improve the Diagnosis of Invasive Mould Disease in Patients with Haematological Malignancies: A Pilot Clinical Study. 9<sup>th</sup> Advances in Aspergillosis and Mucormycosis Meeting, Lugano, Switzerland.

## Web Content

- Echinocandin Antifungals Monograph, Up to Date [http://www.uptodate.com](http://www.uptodate.com/) 
- Mycoses Study Group/Doctor Fungus Website. [http://www.doctorfungus.org/](http://www.doctorfungus.org/)
- Doctor Fungus Website Editor, Antifungal Pharmacology Pages, 2001-2012. [http://www.doctorfungus.org](http://www.doctorfungus.org/) (2002-2007)
- Pharmacoeconomic of antifungal therapy-Primary and Secondary Costs. Dr. Fungus Website [http://www.doctorfungus.org/](http://www.doctorfungus.org/)
- Pharmacokinetic optimization of itraconazole therapy. 
 <br> Fungal Research Trust- Aspergillus Website (Dr. David Denning, Editor) [http://www.aspergillus.man.ac.uk](http://www.aspergillus.man.ac.uk/)
- Antifungal Pharmacology Module. Fungal Research Trust-Aspergillus Website (Dr. David Denning, Editor) [http://www.aspergillus.man.ac.uk](http://www.aspergillus.man.ac.uk/)

## Editorial Boards

`2022`
__Senior Editor, Pharmacokinetics/Pharmacodynamics Section, Journal of Antimicrobial Chemotherapy__
<br> British Socieity of Antimicrobial Chemotherapy

`2016-2021`
__Associate Editor, Journal of Antimicrobial Chemotherapy__
<br> British Socieity of Antimicrobial Chemotherapy

`2013-2020`
__Deputy Editor, Mycoses__
<br> Deutschsprachige Mykologische Gesellschaft

`2013-2015`
__Editor, Current Fungal Infection Reports__
<br> Springer Publishing

`2006-present`
__Editorial board, Antimicrobial Agents Chemotherapy__
<br> American Society for Microbiology

`2006-2011`
__Editorial board, Pharmacotherapy__
<br> American College of Clinical Pharmacy

## Grant or guideline committees 

`2022-present`
Medical Research Council, Infection and Immunity Section, United Kingdom

`2019-present`
French -German Call for Projects on Antimicrobial Resistance AMR 

`2019-present`
European Society for Clinical Microbiology and Infectious Diseases 

`2019-present`
European Congress on Clinical Microbiology and Infectious Diseases 

`2016-present`
British Society for Antimicrobial Chemotherapy 

`2018-present`
Foundation for Polish Science

`2015`
European Committee on Infections in Leukemia-6 (ECIL-6): Guidelines.
<br> Antifungal pharmacology and therapeutic drug monitoring committee chair

`2014`
European Society of Clinical Microbiology and Infectious Diseases
<br> Aspergillosis Guidelines Committee Chair: Pharmacology Section

`2011-present`
Mycoses Study Group Education and Research Consortium, [http://msgerc.org/]__(http://msgerc.org/) 

`2011`
Infectious Diseases Pharmacology Reviewer, Austrian Science Fund

`2010`
NIH/NIAID RFA AI-09-026 and -029, Partnerships for Development of Therapeutics and Diagnostics for Drug-Resistant Bacteria and Eukaryotic Parasites

`2010`
External Ad-Hoc Reviewer, U.S. Armed Forces IRB

`2010`
Ad-Hoc Reviewer, National Aeronautics and Space Administration (NASA)

`2011-present`
Netherlands Organization for Scientific Research. Council for the Earth and Life Sciences Grant

`2009`
University of Texas NIH SCORE Proposals

`2006`
European Commission. Program for Research, Technological Development and Demonstration- Infectious Diseases., 6<sup>th</sup> Framework Programme

## Service

__University of Bologna__
<br>
`2015-present`
English Medical School Curriculum Development Committee
Consiglio del CdL in Medicine and Surgery


__University of Houston__
<br>
`2006-2011`
University of Houston Research Council 2004-2006 

`2006-2011`
University Institution Biosafety Committee 

`2004-2005`
Chair, UH College of Pharmacy Research Committee 

`2007-2010`
UH College of Pharmacy P&T Committee 

`2000-2007`
UH College of Pharmacy Research Committee

`2000-2007`
UH College of Pharmacy Graduate Affairs Committee

`2003`
UH College of Pharmacy Education Subcommittee on Curricular Issues

`2002-2004`
UH Library and Information Technology Committee 2002-2004

`2009-2011`
UH College of Pharmacy AACP Accreditation Self-Study Committee 2009-2011

__National__
<br>
`2008-2010`
Society of Infectious Diseases Pharmacists (SIDP) Board of Directors (national elected position) 

`2002-2004`
Chair, ASHP Clinical Practice Network-Infectious Diseases

`2003-2009`
Society of INfectious Diseases Pharmacists (SIDP) Research Committee 2003-2009; Chair (2007-2009)

`2001-2002`
Chair, Internet Committee, Society of Infectious Disease Pharmacists 

`2001-2002`
Guidelines and Publications Committee, American Society of Clinical Pharmacy 

`1998-1999`
Publications Committee, Society of Infectious Diseases Pharmacists

`1998-1999`
Publications Committee, Americal College of CLinical Pharmacy, Infectious Diseases

## Awards
<br>
`1995` 
Facts and Comparison Excellence in Clinical Medical Communications

`1999` 
ACCP Best poster award finalist

`2002` 
Outstanding Faculty Achievement in Research Award, University of Houston

`2002` 
Manuscript Selected-ASM News Journal Highlights (May 2002)

`2002` 
Phi Lambda Sigma Honorary Faculty Lifetime Member Inductee

`2002` 
Society of Infectious Diseases Pharmacists Young Investigator of the Year Award

`2004` 
University of Houston College of Pharmacy Clinical Faculty Preceptor of the Year

`2004` 
Merck Award for Outstanding Achievement in Pharmacy Education

`2005` 
Fellow, American College of Clinical Pharmacy

`2005` 
University of Houston College of Pharmacy Award for Outstanding Faculty Service

`2009` 
University of Houston College of Pharmacy Award for Outstanding Research Achievement

`2010` 
University of Houston College of Pharmacy Faculty Clinical Preceptor of the Year

`2010` 
University of Houston Award for Excellence in Faculty Research-Associate Professor Level <br> (University-wide award voted by committee of faculty from across the University